#/home/loginuser/.cache/containers/short-name-aliases.conf
[aliases]
  "amir20/dozzle" = "docker.io/amir20/dozzle"
  nginx = "docker.io/library/nginx"
  grafana = "docker.io/grafana"
  "graphiteapp/graphite-statsd" = "docker.io/graphiteapp/graphite-statsd"
