{
 "title": "Incomplete Events",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Incomplete events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(keepLastValue(icarus.evb*.*.Incomplete_Events_Released_to_art_this_run,10))"
    }
   ]
  },
  {
   "title": "Incomplete Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Incomplete_Events_Released_to_art_this_run, 10)), \"Total incomplete events\")"
    }
   ]
  },
  {
   "title": "Rate of Incomplete Events",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(sumSeries(keepLastValue(icarus.evb*.EventBuilder*.Incomplete_Events_Released_to_art_this_run, 10)))"
    }
   ]
  },
  {
   "title": "Rate of Incomplete Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "target": "alias(perSecond(sumSeries(keepLastValue(icarus.evb*.EventBuilder*.Incomplete_Events_Released_to_art_this_run, 10))), \"Rate of incomplete events\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(icarus.evb*.*.Incomplete_Events_Released_to_art_this_run, 10), 2)"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(icarus.evb*.*.Incomplete_Events_Released_to_art_this_run, 10),2)"
    }
   ]
  },
  { "title": "PMT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Missing PMT fragments",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "groupByNode(icarus.evb*.*.PMT.*.*.MissingFragments, 5, \"sumSeries\")"
    }
   ]
  },
  {
   "title": "Empty PMT fragments",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "groupByNode(icarus.evb*.*.PMT.*.*.EmptyFragments, 5, \"sumSeries\")"
    }
   ]
  },
  {
   "title": "Missing PMT fragments",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "target": "groupByNode(icarus.evb*.*.PMT.*.*.MissingFragments, 5, \"sumSeries\")"
    }
   ]
  },
  {
   "title": "Empty PMT fragments",
   "type": "status-history",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "target": "groupByNode(icarus.evb*.*.PMT.*.*.EmptyFragments, 5, \"sumSeries\")"
    }
   ]
  },
  { "title": "TPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Missing TPC fragments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "target": "groupByNode(icarus.evb*.*.TPC.*.*.MissingFragments, 5, \"sumSeries\")"
    }
   ]
  },
  {
   "title": "Missing TPC EAST fragments",
   "type": "status-history",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "target": "groupByNode(icarus.evb*.*.TPC.*.tpce*.MissingFragments, 5, \"sumSeries\")"
    }
   ]
  },
  {
   "title": "Missing TPC WEST fragments",
   "type": "status-history",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "target": "groupByNode(icarus.evb*.*.TPC.*.tpcw*.MissingFragments, 5, 'sumSeries')"
    }
   ]
  },
  { "title": "CRT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Missing CRT fragments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "target": "aliasByNode(icarus.evb*.*.CRT.*.*.MissingFragments, 5)"
    }
   ]
  },
  {
   "title": "Empty CRT fragments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "target": "groupByNode(icarus.evb*.*.CRT.*.*.MissingFragments, 5, \"sumSeries\")"
    }
   ]
  },
  {
   "title": "Missing CRT fragments",
   "type": "status-history",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "target": "aliasByNode(icarus.evb*.*.CRT.*.*.MissingFragments, 5)"
    }
   ]
  },
  {
   "title": "Empty CRT fragments",
   "type": "status-history",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "target": "aliasByNode(icarus.evb*.*.CRT.*.*.EmptyFragments, 5)"
    }
   ]
  }
 ]
}