{
 "title": "SuperNova DAQ Status",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Event Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "keepLastValue(alias(sumSeries(sbnd.evb0*.*.Events_Released_to_art_this_run), 'Running'), 10)"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Last Run Number (partition 1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition1.run_number" }
   ]
  },
  {
   "title": "SN DMA Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 6 },
   "targets": [
    {
     "target": "alias(sbnd.tpc01.BoardReader.*.SN_WritetoDisk_Count, 'tpc01')"
    },
    {
     "target": "alias(sbnd.tpc02.BoardReader.*.SN_WritetoDisk_Count, 'tpc02')"
    },
    {
     "target": "alias(sbnd.tpc03.BoardReader.*.SN_WritetoDisk_Count, 'tpc03')"
    },
    {
     "target": "alias(sbnd.tpc04.BoardReader.*.SN_WritetoDisk_Count, 'tpc04')"
    },
    {
     "target": "alias(sbnd.tpc05.BoardReader.*.SN_WritetoDisk_Count, 'tpc05')"
    },
    {
     "target": "alias(sbnd.tpc06.BoardReader.*.SN_WritetoDisk_Count, 'tpc06')"
    },
    {
     "target": "alias(sbnd.tpc07.BoardReader.*.SN_WritetoDisk_Count, 'tpc07')"
    },
    {
     "target": "alias(sbnd.tpc08.BoardReader.*.SN_WritetoDisk_Count, 'tpc08')"
    },
    {
     "target": "alias(sbnd.tpc09.BoardReader.*.SN_WritetoDisk_Count, 'tpc09')"
    },
    {
     "target": "alias(sbnd.tpc10.BoardReader.*.SN_WritetoDisk_Count, 'tpc10')"
    },
    {
     "target": "alias(sbnd.tpc11.BoardReader.*.SN_WritetoDisk_Count, 'tpc11')"
    }
   ]
  },
  {
   "title": "SN DIsk Write Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "target": "alias(sbnd.tpc01.BoardReader.*.SN_WritetoDisk_Count, 'tpc01')"
    },
    {
     "target": "alias(sbnd.tpc02.BoardReader.*.SN_WritetoDisk_Count, 'tpc02')"
    },
    {
     "target": "alias(sbnd.tpc03.BoardReader.*.SN_WritetoDisk_Count, 'tpc03')"
    },
    {
     "target": "alias(sbnd.tpc04.BoardReader.*.SN_WritetoDisk_Count, 'tpc04')"
    },
    {
     "target": "alias(sbnd.tpc05.BoardReader.*.SN_WritetoDisk_Count, 'tpc05')"
    },
    {
     "target": "alias(sbnd.tpc06.BoardReader.*.SN_WritetoDisk_Count, 'tpc06')"
    },
    {
     "target": "alias(sbnd.tpc07.BoardReader.*.SN_WritetoDisk_Count, 'tpc07')"
    },
    {
     "target": "alias(sbnd.tpc08.BoardReader.*.SN_WritetoDisk_Count, 'tpc08')"
    },
    {
     "target": "alias(sbnd.tpc09.BoardReader.*.SN_WritetoDisk_Count, 'tpc09')"
    },
    {
     "target": "alias(sbnd.tpc10.BoardReader.*.SN_WritetoDisk_Count, 'tpc10')"
    },
    {
     "target": "alias(sbnd.tpc11.BoardReader.*.SN_WritetoDisk_Count, 'tpc11')"
    }
   ]
  },
  {
   "title": "Event Builder Data Rate ",
   "type": "gauge",
   "description": "rate in bytes/second of data on all eventbuilders",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(sbnd.evb0*.*.Data_Rate)"
    }
   ]
  },
  {
   "title": "/data Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.sbnd-evb*.data.Percent_Used, 1)"
    },
    {
     "target": "alias(sbnd.sbnd-evb01.daq_log.Percent_Used, 'daq_log')"
    }
   ]
  },
  {
   "title": "/data Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.sbnd-tpc{01,02,03,04,05,06,07,08,09,10,11}.data.Percent_Used, 1)"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Board Readers Data Rate ",
   "type": "timeseries",
   "description": "Data rate of each board reader (TPC not working...)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.tpc*.BoardReader.*.Data_Rate), 'TPCs')"
    }
   ]
  },
  {
   "title": "Event Builder Data Rate ",
   "type": "timeseries",
   "description": "rate in bytes/second of data on all eventbuilders",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "sumSeries(sbnd.evb0*.*.Data_Rate)"
    }
   ]
  }
 ]
}