{
 "title": "Shifter DAQ Status",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Event Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "keepLastValue(alias(sumSeries(sbnd.evb0*.*.Events_Released_to_art_this_run), 'Running'), 10)"
    }
   ]
  },
  {
   "title": "Last Run Number (partition 1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition1.run_number" }
   ]
  },
  {
   "title": "Event Rates",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "alias(diffSeries(sumSeries(#H)), 'Total Event Rate')",
     "targetFull": "alias(diffSeries(sumSeries(alias(sumSeries(keepLastValue(sbnd.evb*.*.Event_Rate, 10)), 'EventBuilder Event Rate'))), 'Total Event Rate')"
    },
    {
     "target": "alias(keepLastValue(sumSeries(keepLastValue(sbnd.disp01.*.Event_Rate, 10)), 10), 'Dispatcher Event Rate')"
    }
   ]
  },
  {
   "title": "TDC Sample Rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan0_Sample_Rate), 'Chan 0 - CRT T1 Reset')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan1_Sample_Rate), 'Chan 1 - BES')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan2_Sample_Rate), 'Chan 2 - RWM')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan3_Sample_Rate), 'Chan 3 - FTrig')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan4_Sample_Rate), 'Chan 4 - ETrig')"
    }
   ]
  },
  {
   "title": "TDC Sample Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan0_Sample_Rate), 'Chan 0 - CRT T1 Reset')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan1_Sample_Rate), 'Chan 1 - BES')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan2_Sample_Rate), 'Chan 2 - RWM')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan3_Sample_Rate), 'Chan 3 - FTrig')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan4_Sample_Rate), 'Chan 4 - ETrig')"
    },
    { "expression": "$E / $F", "type": "math" }
   ]
  },
  {
   "title": "Total Missing fragments ",
   "type": "stat",
   "description": "Number of events with mising fragments",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb01*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb02*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb03*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb04*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb05*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb06*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb07*.*.EventsWithMissingFragments, 10)), 'Total missing fragments')"
    }
   ]
  },
  {
   "title": "Light Trigger Rates",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(keepLastValue(sbnd.ptb.*.*.PTB_LLT_14_rate, 10)), 'Total Low Level  Light Rate')"
    },
    {
     "target": "alias(derivative(sbnd.ptb.BoardReader.8.PTB_LLT_14_rate), 'Change in rate')"
    }
   ]
  },
  {
   "title": "BNB Signals",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "currentAbove(alias(averageSeries(keepLastValue(sbnd.ptb.BoardReader.*.PTB_LLT_28_rate, 10)), '$1D (Beam Intended for BNB)'), -1)"
    },
    {
     "target": "currentAbove(alias(averageSeries(keepLastValue(sbnd.tdc.BoardReader.*.TDC_Chan1_Sample_Rate, 10)), 'BES (Beam Early Warning)'), -1)"
    },
    {
     "target": "currentAbove(alias(averageSeries(keepLastValue(sbnd.tdc.BoardReader.*.TDC_Chan2_Sample_Rate, 10)), 'RWM (Beam At SBND)'), -1)"
    }
   ]
  },
  {
   "title": "Events with empty fragments  [%]",
   "type": "stat",
   "description": "the rate of the total empty fragments collected normalized to the total number of events collected",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  { "title": "NTB/FEM Asynchronization", "type": "library-panel-ref", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 } },
  {
   "title": "PTB  Low Level Light Trigger Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_20_rate, 'Flash LLT rate: MTCA HI')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_21_rate, 'Event LLT rate: MTCA MED')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_18_rate, 'MTCA LO')"
    }
   ]
  },
  {
   "title": "RWM rate",
   "type": "timeseries",
   "description": "Rate of the resistive wall monitor signal from AD (shows beam rates)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.TDC_Chan2_Sample_Rate), 'Chan 2 - RWM')"
    }
   ]
  },
  {
   "title": "Event Builder Data Rate ",
   "type": "gauge",
   "description": "rate in bytes/second of data on all eventbuilders",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(sbnd.evb0*.*.Data_Rate)"
    }
   ]
  },
  {
   "title": "Dispatcher Data Rate ",
   "type": "gauge",
   "description": "rate in bytes/second of data on all dispatchers",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(sbnd.disp*.*.Data_Rate)"
    }
   ]
  },
  {
   "title": "evb:/data Usage Monitor -- Contact sbnd-data-expert",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.sbnd-evb*.data.Percent_Used, 1)"
    },
    {
     "target": "alias(sbnd.sbnd-evb01.daq_log.Percent_Used, 'daq_log')"
    }
   ]
  },
  { "title": "SuperNova Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "TPC15 Status",
   "type": "stat",
   "description": "Is tpc15 on and updating",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.sbnd-tpc15.data.Percent_Used, 1)"
    }
   ]
  },
  {
   "title": "SN On",
   "type": "stat",
   "description": "Has the SN stream turned off by SN-stop function.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(\n  minSeries(\n    sbnd.tpc{01,02,03,04,05,06,08,09,10,11,12}.BoardReader.*.SN_Stream_Stopped\n  ),\n  'SN Stream Status'\n)"
    }
   ]
  },
  {
   "title": "TPC:/data Usage Monitor - Contact sbnd-daq-expertt",
   "type": "gauge",
   "description": "Shows how much of the /data area on tpc is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.sbnd-tpc{01,02,03,04,05,06,08,09,10,11,12,15,18}.data.Percent_Used, 1)"
    }
   ]
  },
  {
   "title": "SN DMA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "target": "aliasByNode(\n  sbnd.tpc{01,02,03,04,05,06,08,09,10,11,12}.BoardReader.*.SN_DMA_Count,\n  1\n)"
    }
   ]
  },
  {
   "title": "SN Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "target": "aliasByNode(\n  sbnd.tpc{01,02,03,04,05,06,08,09,10,11,12}.BoardReader.*.SN_WritetoDisk_Count,\n  1\n)"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Events current run",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 49 },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.evb*.EventBuilder*.Events_Released_to_art_this_run), 'Total Events This Run')"
    }
   ]
  },
  {
   "title": "Missing/Empty fragments",
   "type": "stat",
   "description": "Number of events with mising fragments",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Events_Released_to_art_this_run, 10)), 'Total Events')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.EventsWithEmptyFragments, 10)), 'Events wth empty fragments')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.EventsWithMissingFragments, 10)), 'Events with missing fragments')"
    }
   ]
  },
  {
   "title": "Events Released To Art From This Run",
   "type": "stat",
   "description": "This shows the number of events collected for this run.",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.dl*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.disp*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in Dispatchers')"
    }
   ]
  },
  {
   "title": "Incomplete Events Released To Art From This Run",
   "type": "stat",
   "description": "In the ideal case, there are no incomplete events. If you start seeing incomplete events, make note of this in the ECL!",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Incomplete Events in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.dl*.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Inomplete Events in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.disp01.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Inomplete Events in Dispatchers')"
    }
   ]
  },
  {
   "title": "Golden Neutrino Stream Rate ",
   "type": "gauge",
   "description": "GNS selection rate (5 minute average)",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "movingAverage(sumSeries(currentAbove(sbnd.evb*.EventBuilder*.Neutrino_Stream_Rate, -1)), '5min')"
    }
   ]
  },
  {
   "title": "Fragment Rates",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(keepLastValue(sbnd.*pmt*.BoardReader.*.Fragment_Rate, 10)), 'PMT Avg Fragment Rate')"
    },
    {
     "target": "alias(averageSeries(keepLastValue(sbnd.tpc*.BoardReader.*.Fragment_Rate, 10)), 'TPC Avg Fragment Rate')"
    },
    {
     "target": "alias(averageSeries(keepLastValue(sbnd.*crt*.BoardReader.*.Fragment_Rate, 10)), 'CRT Avg Fragment Rate')"
    },
    {
     "target": "alias(averageSeries(keepLastValue(sbnd.*tdc*.BoardReader.*.Fragment_Rate, 10)), 'TDC Avg Fragment Rate')"
    },
    {
     "target": "alias(averageSeries(keepLastValue(sbnd.*ptb*.BoardReader.*.Fragment_Rate, 10)), 'PTB Avg Fragment Rate')"
    }
   ]
  },
  {
   "title": "Average TPC FEM rate ",
   "type": "timeseries",
   "description": "Total FEM Fragment Rate/ number of total FEMs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "target": "alias(scale(sumSeries(sbnd.tpc*.BoardReader.*.Fragment_Rate), 0.00571428571429), 'Average FEM fragment rate')"
    }
   ]
  },
  {
   "title": "Event Builder Event Rates",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb01.*.Event_Rate, 10)), 'EventBuilder1')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb02.*.Event_Rate, 10)), 'EventBuilder2')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb03.*.Event_Rate, 10)), 'EventBuilder3')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb04.*.Event_Rate, 10)), 'EventBuilder4')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb05.*.Event_Rate, 10)), 'EventBuilder5')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb06.*.Event_Rate, 10)), 'EventBuilder6')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb07.*.Event_Rate, 10)), 'EventBuilder7')"
    }
   ]
  },
  {
   "title": "Event Rates including spare",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "alias(keepLastValue(sumSeries(keepLastValue(sbnd.evb0*.*.Event_Rate, 10)), 10), 'Total Event Rate')"
    },
    {
     "target": "alias(keepLastValue(sumSeries(keepLastValue(sbnd.disp01.*.Event_Rate, 10)), 10), 'Dispatcher Event Rate')"
    }
   ]
  },
  { "title": "Memory & Data rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Event Builder Data Rate ",
   "type": "timeseries",
   "description": "rate in bytes/second of data on each event builder (stacked)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "target": "sbnd.evb*.*.Data_Rate" }
   ]
  },
  {
   "title": "Event Builder Data Rate ",
   "type": "timeseries",
   "description": "rate in bytes/second of data on all eventbuilders",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "sumSeries(sbnd.evb0*.*.Data_Rate)"
    }
   ]
  },
  {
   "title": "Shared Memory % Full",
   "type": "timeseries",
   "description": "Shared Memory % Full of event builders",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.evb01*.*.Shared_Memory_Full_%), 'evb01')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb02*.*.Shared_Memory_Full_%), 'evb02')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb03*.*.Shared_Memory_Full_%), 'evb03')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb04*.*.Shared_Memory_Full_%), 'evb04')"
    }
   ]
  },
  {
   "title": "Board Readers Data Rate ",
   "type": "timeseries",
   "description": "Data rate of each board reader (TPC not working...)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.pmt*.BoardReader.*.Data_Rate), 'PMTs')"
    },
    {
     "target": "alias(sumSeries(sbnd.crt*.BoardReader.*.Data_Rate), 'CRTs')"
    },
    {
     "target": "alias(sumSeries(sbnd.ptb.BoardReader.*.Data_Rate), 'PTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.tpc*.BoardReader.*.Data_Rate), 'TPCs')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.Data_Rate), 'TDC')"
    },
    {
     "target": "alias(sumSeries(sbnd.xarapuca*.BoardReader.*.Data_Rate), 'XAs')"
    }
   ]
  },
  {
   "title": "Evb1-7 Missing fragments ",
   "type": "timeseries",
   "description": "Number of events with missing fragments",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb01*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb02*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb03*.*.EventsWithMissingFragments, 10),keepLastValue(sbnd.evb04*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb05*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb06*.*.EventsWithMissingFragments, 10), keepLastValue(sbnd.evb07*.*.EventsWithMissingFragments, 10)), 'Total missing fragments')"
    }
   ]
  },
  {
   "title": "BoardReader.*.Fragment_Buffer_Full_%",
   "type": "timeseries",
   "description": "sbnd.*.BoardReader.*.Fragment_Buffer_Full_%",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "sbnd.*.BoardReader.*.Fragment_Buffer_Full_%"
    }
   ]
  },
  {
   "title": "BoardReader Data Rate",
   "type": "timeseries",
   "description": "Total Data Rate from a Board Reader Subsystem",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.*.BoardReader.*.Data_Rate), 'Total')"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.crt*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.pmt*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.tpc*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.ntb*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.ptb*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.tdc*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.xarapuca*.BoardReader.*.Data_Rate), 1)"
    }
   ]
  },
  {
   "title": "All Evb Missing/Empty fragments ",
   "type": "timeseries",
   "description": "Number of events with mising fragments",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb0*.*.EventsWithMissingFragments, 10)), 'Total missing fragments')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb0*.*.EventsWithEmptyFragments, 10)), 'Total empty fragments')"
    }
   ]
  },
  {
   "title": "BoardReader Data Rate",
   "type": "timeseries",
   "description": "Total Data Rate from a Board Reader Subsystem",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.*.BoardReader.*.Fragment_Rate), 'Total')"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.crt*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.pmt*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.tpc*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.ntb*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.ptb*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.tdc*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.xarapuca*.BoardReader.*.Data_Rate), 1)"
    }
   ]
  }
 ]
}