{
 "title": "CRT Monitor",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Run Number (P 2)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition2.run_number" }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 1 },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Fragment_Rate, 1), 1), 0)"
    }
   ]
  },
  {
   "title": "Collected Events Monitor",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.dl*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in DataLoggers')"
    },
    {
     "target": "currentAbove(alias(sbnd.evb04.EventBuilder4*.Events_Released_to_art_this_run, 'Events Released to art in EventBuilder4'), -1)"
    },
    {
     "target": "alias(sumSeries(currentAbove(keepLastValue(sbnd.crteast*.BoardReader.*.Fragment_Count, 10), -1)), 'Fragments Sent from East CRT')"
    },
    {
     "target": "alias(sumSeries(currentAbove(keepLastValue(sbnd.crtnorth*.BoardReader.*.Fragment_Count, 10), -1)), 'Fragments Sent from North CRT')"
    },
    {
     "target": "alias(sumSeries(currentAbove(keepLastValue(sbnd.crtflat*.BoardReader.*.Fragment_Count, 10), -1)), 'Fragments Sent from Bottom CRT')"
    }
   ]
  },
  {
   "title": "Fragment Watcher",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(sbnd.evb04.*.EventsProcessed), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb04.*.EventsWithEmptyFragments), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb04.*.EventsWithMissingFragments), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb04.EventBuilder4*.Incomplete_Event_Rate), 3)"
    }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Fragment_Rate, 1), 1), -1)"
    }
   ]
  },
  {
   "title": "CRT Sample Rate (All FEBs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "currentAbove(sbnd.crt*.BoardReader.*.FragmentsBuilt*, -1)"
    }
   ]
  },
  {
   "title": "Empty Fragments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "sbnd.evb04.*.EventsWithEmptyFragments"
    }
   ]
  },
  {
   "title": "Missing Fragments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "target": "sbnd.evb04.*.EventsWithMissingFragments"
    }
   ]
  },
  {
   "title": "/data Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sbnd.sbnd-evb04.data.Percent_Used, 'sbnd-evb04')"
    }
   ]
  },
  {
   "title": "CRT Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "T1 Resets Per Event",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "target": "sbnd.evb*.EventBuilder*.T1_resets_per_event"
      }
     ]
    },
    {
     "title": "CRT Hits Per Plane During Beam Spill",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "target": "groupByNode(currentAbove(alias(sbnd.*.*.CRT_hits_beam_plane_0, 'Bottom'), -1), 0, 'sum')"
      },
      {
       "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_1, 3), 'South (upstream)'), -1), 0, 'sum')"
      },
      {
       "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_2, 3), 'North (downstream)'), -1), 0, 'sum')"
      },
      {
       "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_3, 3), 'West (left)'), -1), 0, 'sum')"
      },
      {
       "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_4, 3), 'East (right)'), -1), 0, 'sum')"
      },
      {
       "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_5, 3), 'Top Low'), -1), 0, 'sum')"
      },
      {
       "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_6, 3), 'Top High'), -1), 0, 'sum')"
      }
     ]
    },
    {
     "title": "Missing PPS",
     "type": "status-history",
     "gridPos": { "h": 37, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "target": "currentAbove(sbnd.*.BoardReader.*.FEB_missing_PPS_*, -1)"
      }
     ]
    },
    {
     "title": "Missing T1",
     "type": "status-history",
     "gridPos": { "h": 37, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "target": "currentAbove(sbnd.crt*.BoardReader.*.FEB_missing_T1_*, -1)"
      }
     ]
    }
   ]
  },
  {
   "title": "CRT Expert Plots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Hits Per Poll",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "target": "averageAbove(aliasByNode(sbnd.crt*.BoardReader.*.total_hits_per_poll, 1), -1)"
      }
     ]
    },
    {
     "title": "Time Reading FEBs (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "target": "currentAbove(aliasByNode(sbnd.crt*.BoardReader.*.time_reading_FEBs_ms, 1), -1)"
      }
     ]
    },
    {
     "title": "GetFEBData() Time (ms)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "target": "currentAbove(aliasByNode(sbnd.crt*.BoardReader.*.GetFEBData_execution_time_ms, 1), -1)"
      }
     ]
    },
    {
     "title": "Max FEB Buffer Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "target": "currentAbove(aliasByNode(sbnd.crt*.BoardReader.*.max_feb_buffer_size, 1), -1)"
      }
     ]
    },
    {
     "title": "FEB Poll Period (ms)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "target": "currentAbove(aliasByNode(sbnd.crt*.BoardReader.*.feb_poll_period_ms_*, 1, 4), -1)"
      }
     ]
    },
    {
     "title": "FEB Hit Rate (Hz)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "target": "currentAbove(aliasByNode(sbnd.crt*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4), -1)"
      }
     ]
    },
    {
     "title": "FEB Poll Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "target": "currentAbove(aliasByNode(sbnd.crt*.BoardReader.*.feb_poll_time_ms_*, 1, 4), -1)"
      }
     ]
    }
   ]
  },
  { "title": "Individual Wall Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Top High FEB Hit Rate (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(sbnd.crttophigh*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4), -1)"
    }
   ]
  },
  {
   "title": "Top Low FEB Hit Rate (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(sbnd.crttoplow*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4), -1)"
    }
   ]
  },
  {
   "title": "North FEB Hit Rate (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(sbnd.crtnorth*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4), -1)"
    }
   ]
  },
  {
   "title": "South FEB Hit Rate (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(sbnd.crtsouth*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4), -1)"
    }
   ]
  },
  {
   "title": "West FEB Hit Rate (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(sbnd.crtwest*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4), -1)"
    }
   ]
  },
  {
   "title": "East FEB Hit Rate (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(sbnd.crteast*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4), -1)"
    }
   ]
  },
  {
   "title": "Flat FEB Hit Rate (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(sbnd.crtflat*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4), -1)"
    },
    {
     "target": "currentAbove(aliasByNode(sbnd.crtminos*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4), -1)"
    }
   ]
  },
  {
   "title": "Wall Rolling Average Rates (Hz)",
   "type": "timeseries",
   "description": "Each wall gives the averaged rate across all boards then averaged over 10mins",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "target": "alias(movingAverage(averageSeries(currentAbove(sbnd.crttophigh*.BoardReader.*.feb_hit_rate_Hz_*, -1)), '10min'), 'Top High')"
    },
    {
     "target": "alias(movingAverage(averageSeries(currentAbove(sbnd.crttoplow*.BoardReader.*.feb_hit_rate_Hz_*, -1)), '10min'), 'Top Low')"
    },
    {
     "target": "alias(movingAverage(averageSeries(currentAbove(sbnd.crtwest*.BoardReader.*.feb_hit_rate_Hz_*, -1)), '10min'), 'West')"
    },
    {
     "target": "alias(movingAverage(averageSeries(currentAbove(sbnd.crteast*.BoardReader.*.feb_hit_rate_Hz_*, -1)), '10min'), 'East')"
    },
    {
     "target": "alias(movingAverage(averageSeries(currentAbove(sbnd.crtnorth*.BoardReader.*.feb_hit_rate_Hz_*, -1)), '10min'), 'North')"
    },
    {
     "target": "alias(movingAverage(averageSeries(currentAbove(sbnd.crtsouth*.BoardReader.*.feb_hit_rate_Hz_*, -1)), '10min'), 'South')"
    },
    {
     "target": "alias(movingAverage(averageSeries(currentAbove(sbnd.crtflat*.BoardReader.*.feb_hit_rate_Hz_*, -1)), '10min'), 'Flat')"
    }
   ]
  },
  {
   "title": "Event Building",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "EVB04 Fragment Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.evb04.EventBuilder*.Event_Rate, 1)"
      }
     ]
    },
    {
     "title": "Request Response Time",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "currentAbove(aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Request_Response_Time, 1), 1), -1)"
      }
     ]
    },
    {
     "title": "BoardReader applyRequests() loop Avg Time",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "currentAbove(aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Avg_Request_Response_Wait_Time, 1), 1), -1)"
      }
     ]
    },
    {
     "title": "EVB04 Memory Full %",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasSub(keepLastValue(sbnd.evb04.EventBuilder*.Shared_Memory_Full_%, 10), '.*Builder(\\d+).*', '\\1')"
      }
     ]
    },
    {
     "title": "EVB04  Pending Buffers",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 58 },
     "targets": [
      {
       "target": "aliasSub(movingAverage(sbnd.evb04.EventBuilder*.Shared_Memory_Pending_Buffers, 1), '.*Builder(\\d+).*', '\\1')"
      }
     ]
    },
    {
     "title": "EVB04  Full Buffers",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.evb04.EventBuilder*.Shared_Memory_Full_Buffers, 1), 2)"
      }
     ]
    }
   ]
  },
  { "title": "Software Trigger Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Golden Neutrino Stream Rate ",
   "type": "gauge",
   "description": "GNS selection rate (5 minute average)",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "movingAverage(sumSeries(currentAbove(sbnd.evb*.EventBuilder*.Neutrino_Stream_Rate, -1)), '5min')"
    }
   ]
  },
  {
   "title": "Software Trigger PMTs Above Threshold",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 65 },
   "targets": [
    {
     "target": "currentAbove(sbnd.evb*.EventBuilder*.PMT_SWTrig_nAboveThreshold, -1)"
    }
   ]
  },
  {
   "title": "CRT Hits Per Plane During Beam Spill",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "target": "groupByNode(currentAbove(alias(sbnd.*.*.CRT_hits_beam_plane_0, 'Bottom'), -1), 0, 'sum')"
    },
    {
     "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_1, 3), 'South (upstream)'), -1), 0, 'sum')"
    },
    {
     "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_2, 3), 'North (downstream)'), -1), 0, 'sum')"
    },
    {
     "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_3, 3), 'West (left)'), -1), 0, 'sum')"
    },
    {
     "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_4, 3), 'East (right)'), -1), 0, 'sum')"
    },
    {
     "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_5, 3), 'Top Low'), -1), 0, 'sum')"
    },
    {
     "target": "groupByNode(currentAbove(alias(aliasByNode(sbnd.*.*.CRT_hits_beam_plane_6, 3), 'Top High'), -1), 0, 'sum')"
    }
   ]
  },
  {
   "title": "Golden Neutrino Stream Rate ",
   "type": "timeseries",
   "description": "GNS selection rate",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "target": "sumSeries(currentAbove(sbnd.evb*.EventBuilder*.Neutrino_Stream_Rate, -1))"
    }
   ]
  },
  {
   "title": "CRT Hits During Beam Spill T1 Time",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "currentAbove(sbnd.evb*.*.CRT_T1_in_beam, -1)"
    }
   ]
  },
  {
   "title": "CRT pedestals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Pedestal by FEB #,  For Channel 0",
     "type": "timeseries",
     "description": "The average pedestal (adc value on t0 or t1 reset) for channel 0 of each FEB",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 69 },
     "targets": [
      {
       "refCount": -1,
       "target": "sbnd.*.BoardReader.1.pedestal_adc_feb*_ch0"
      }
     ]
    },
    {
     "title": "CRT Pedestal Stddevs by FEB - Ch 0",
     "type": "timeseries",
     "description": "Standard deviations in the FEB pedestals for Channel 0 of all FEBs",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "stdev(removeBelowValue(sbnd.*.BoardReader.1.pedestal_adc_feb*_ch0, 0.1), 20, 0.1)"
      }
     ]
    },
    {
     "title": "CRT Pedestal Stddevs  (All FEBs & Channels)",
     "type": "timeseries",
     "description": "Standard deviations in the pedestals for all channels of all FEBs",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "target": "stdev(removeBelowValue(sbnd.*.BoardReader.1.pedestal_adc_feb*_ch*, 0.1), 20, 0.1)"
      }
     ]
    },
    {
     "title": "Average FEB 155 Pedestals",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "refCount": -1,
       "target": "sbnd.*.BoardReader.1.pedestal_adc_feb155_ch*"
      }
     ]
    }
   ]
  },
  {
   "title": "Board Reader Core Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "BoardReader getNext() Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Avg_Output_Wait_Time, 1), 1)"
      }
     ]
    },
    {
     "title": "Artdaq Fragment Buffer % Full",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "currentAbove(aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Fragment_Buffer_Full_%, 1), 1), -1)"
      }
     ]
    },
    {
     "title": "BoardReader applyRequests() loop Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(removeAboveValue(sbnd.crt*.BoardReader.*.Avg_Request_Response_Wait_Time, 0.5), 1), 1)"
      }
     ]
    },
    {
     "title": "BoardReader Fragments per getNext()",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Avg_Frags_Per_Read, 1), 1)"
      }
     ]
    },
    {
     "title": "BoardReader sendFragment() Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Avg_Output_Wait_Time, 1), 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "/data Usage Monitor",
     "type": "gauge",
     "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(sbnd.sbnd-evb01.data.Percent_Used, 'sbnd-evb01')"
      },
      {
       "target": "alias(sbnd.sbnd-evb02.data.Percent_Used, 'sbnd-evb02')"
      },
      {
       "target": "alias(sbnd.sbnd-evb03.data.Percent_Used, 'sbnd-evb03')"
      },
      {
       "target": "alias(sbnd.sbnd-evb04.data.Percent_Used, 'sbnd-evb04')"
      },
      {
       "target": "alias(sbnd.sbnd-evb05.data.Percent_Used, 'sbnd-evb05')"
      },
      {
       "target": "sbnd.sbnd-evb06.data.Percent_Used"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Process_CPU_Usage, 1), 1)"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Process_RAM_Usage, 1), 4)"
      }
     ]
    }
   ]
  }
 ]
}