{
 "title": "Tutorial",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Test Panel",
   "type": "timeseries",
   "description": "test",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    { "target": "sbnd.partition1.run_number" }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Run Number (P 3)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition3.run_number" }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 9 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.crtup01.BoardReader.1.Fragment_Rate, 1), 1)"
    },
    {
     "target": "aliasByNode(movingAverage(sbnd.crtdown01.BoardReader.1.Fragment_Rate, 1), 1)"
    }
   ]
  },
  {
   "title": "Collected Events Monitor",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 9 },
   "targets": [
    {
     "target": "alias(keepLastValue(sbnd.crtup01.BoardReader.*.Fragment_Count, 10), 'Fragments Sent from Upstream CRT')"
    },
    {
     "target": "alias(keepLastValue(sbnd.crtdown01.BoardReader.*.Fragment_Count, 10), 'Fragments Sent from Downstream CRT')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.dl*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.disp*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in Dispatchers')"
    },
    {
     "target": "alias(sbnd.evb03.EventBuilder3_CRTmetric.Events_Released_to_art_this_run, 'Events Released to art in EventBuilder3')"
    }
   ]
  },
  {
   "title": "Fragment Watcher",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(sbnd.evb03.*.EventsProcessed), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb03.*.EventsWithEmptyFragments), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb03.*.EventsWithMissingFragments), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb03.EventBuilder3.Incomplete_Event_Rate), 3)"
    }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Fragment_Rate, 1), 1)"
    }
   ]
  },
  {
   "title": "CRT Sample Rate (All FEBs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "sbnd.crt*.BoardReader.*.FragmentsBuilt*"
    }
   ]
  },
  {
   "title": "Empty Fragments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "target": "sbnd.evb03.*.EventsWithEmptyFragments"
    }
   ]
  },
  {
   "title": "Missing Fragments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "target": "sbnd.evb03.*.EventsWithMissingFragments"
    }
   ]
  },
  { "title": "PMT Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "PMT Fragment Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt03.BoardReader.12.Fragment_Rate, 1)"
    }
   ]
  },
  {
   "title": "PMT Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 24 },
   "targets": [
    {
     "target": "sbnd.pmt03.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "Spec TDC Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "TDC Sample Rate",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sbnd.tdc.*.*.TDC_Chan*_Sample_Rate"
      }
     ]
    },
    {
     "title": "SPEC Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "target": "sbnd.tdc.*.*.SPEC_Temperature" }
     ]
    }
   ]
  },
  {
   "title": "Event Building",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "EVB Fragment Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.evb*.EventBuilder*.Event_Rate, 1)"
      }
     ]
    },
    {
     "title": "Request Response Time",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.crt*01.BoardReader.*.Request_Response_Time, 1), 1)"
      }
     ]
    },
    {
     "title": "BoardReader applyRequests() loop Avg Time",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Avg_Request_Response_Wait_Time, 1), 1)"
      }
     ]
    },
    {
     "title": "EVB Memory Full %",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "target": "aliasSub(keepLastValue(sbnd.evb*.EventBuilder*.Shared_Memory_Full_%, 10), '.*Builder(\\d+).*', '\\1')"
      }
     ]
    },
    {
     "title": "EVB  Pending Buffers",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
     "targets": [
      {
       "target": "aliasSub(movingAverage(sbnd.evb*.EventBuilder*.Shared_Memory_Pending_Buffers, 1), '.*Builder(\\d+).*', '\\1')"
      }
     ]
    },
    {
     "title": "EVB  Full Buffers",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(sbnd.evb*.EventBuilder*.Shared_Memory_Full_Buffers, 1), 2)"
      }
     ]
    }
   ]
  },
  { "title": "CRT Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "T1 Resets Per Event",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "target": "sbnd.evb*.EventBuilder3_nustream*.T1_resets_per_event"
    }
   ]
  },
  {
   "title": "CRT Hits Per Plane",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.evb03.EventBuilder3_*_art1.CRT_hits_beam_plane_*, 3)"
    }
   ]
  },
  {
   "title": "Missing PPS",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*01.BoardReader.*.FEB_missing_PPS_*, 4)"
    }
   ]
  },
  {
   "title": "Missing T1",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*01.BoardReader.*.FEB_missing_T1_*, 4)"
    }
   ]
  },
  {
   "title": "T1 Resets Per Poll",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*01.BoardReader.*.FEB_T1_resets_*, 4)"
    }
   ]
  },
  {
   "title": "Time Reading FEBs (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*.BoardReader.*.time_reading_FEBs_ms, 1)"
    }
   ]
  },
  {
   "title": "Total Hits Per Poll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*.BoardReader.*.total_hits_per_poll, 1)"
    }
   ]
  },
  {
   "title": "Max FEB Buffer Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*.BoardReader.*.max_feb_buffer_size, 1)"
    }
   ]
  },
  {
   "title": "GetFEBData() Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*.BoardReader.*.GetFEBData_execution_time_ms, 1)"
    }
   ]
  },
  {
   "title": "FEB Hit Rate (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*.BoardReader.*.feb_hit_rate_Hz_*, 1, 4)"
    }
   ]
  },
  {
   "title": "FEB Poll Period (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*.BoardReader.*.feb_poll_period_ms_*, 1, 4)"
    }
   ]
  },
  {
   "title": "FEB Poll Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.crt*.BoardReader.*.feb_poll_time_ms_*, 1, 4)"
    }
   ]
  },
  { "title": "Software Trigger Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Golden Neutrino Stream Rate",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sbnd.evb03.EventBuilder3_nustream*.Neutrino_Stream_Rate"
    }
   ]
  },
  { "title": "Board Reader Core Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "BoardReader getNext() Avg Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Avg_Output_Wait_Time, 1), 1)"
    }
   ]
  },
  {
   "title": "Artdaq Fragment Buffer % Full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Fragment_Buffer_Full_%, 1), 1)"
    }
   ]
  },
  {
   "title": "BoardReader applyRequests() loop Avg Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(removeAboveValue(sbnd.crt*.BoardReader.*.Avg_Request_Response_Wait_Time, 0.5), 1), 1)"
    }
   ]
  },
  {
   "title": "BoardReader Fragments per getNext()",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Avg_Frags_Per_Read, 1), 1)"
    }
   ]
  },
  {
   "title": "BoardReader sendFragment() Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Avg_Output_Wait_Time, 1), 1)"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "/data Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sbnd.sbnd-evb01.data.Percent_Used, 'sbnd-evb01')"
    },
    {
     "target": "alias(sbnd.sbnd-evb02.data.Percent_Used, 'sbnd-evb02')"
    },
    {
     "target": "alias(sbnd.sbnd-evb03.data.Percent_Used, 'sbnd-evb03')"
    },
    {
     "target": "alias(sbnd.sbnd-evb04.data.Percent_Used, 'sbnd-evb04')"
    },
    {
     "target": "alias(sbnd.sbnd-evb05.data.Percent_Used, 'sbnd-evb05')"
    },
    {
     "target": "sbnd.sbnd-evb06.data.Percent_Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Process_CPU_Usage, 1), 1)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.crt*.BoardReader.*.Process_RAM_Usage, 1), 4)"
    }
   ]
  }
 ]
}