{
 "title": "icarus_artdaq",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Event Builder Buffer Occupancy",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Buffers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Shared_Memory_Full_Buffers, 100)), ' Full')"
    },
    {
     "target": "alias(maxSeries(keepLastValue(icarus.evb*.*.Shared_Memory_Full_Buffers, 100)), 'Max full ')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Shared_Memory_Reading_Buffers, 100)), 'Reading')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Shared_Memory_Pending_Buffers, 100)), 'Writing')"
    },
    {
     "target": "alias(minSeries(icarus.evb*.*.Shared_Memory_Available_Buffers), 'Min available')"
    }
   ]
  },
  {
   "title": "Event Builders Shared Memory Full %",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(icarus.evb*.*.Shared_Memory_Full_%, 1), 2)"
    }
   ]
  },
  {
   "title": "Back-pressure wait time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "aliasByNode(icarus.evb*.*.Back-pressure_wait_time, 2)"
    },
    {
     "target": "aliasByNode(icarus.disp01.Dispatcher1.Back-pressure_wait_time, 2)"
    }
   ]
  },
  {
   "title": "TPC West Module: Min and Max Fragment Counts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "lowestCurrent(aliasByNode(icarus.tpcw*.BoardReader.*.Fragment_Count, 1), 10)"
    },
    {
     "target": "highestCurrent(aliasByNode(icarus.tpcw*.BoardReader.*.Fragment_Count, 1), 10)"
    }
   ]
  },
  {
   "title": "TPC East Module: Min and Max Fragment Counts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "lowestCurrent(aliasByNode(icarus.tpce*.BoardReader.*.Fragment_Count, 1), 10)"
    },
    {
     "target": "highestCurrent(aliasByNode(icarus.tpce*.BoardReader.*.Fragment_Count, 1), 10)"
    }
   ]
  },
  {
   "title": "TPC Boardreaders: Top 20 Buffer Usage (% by bytes)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(highestMax(keepLastValue(icarus.tpc*.BoardReader.*.Fragment_Buffer_Full_%Bytes, 100), 20), 1)"
    }
   ]
  },
  {
   "title": "PMT Boardreaders: Top 10 Buffer Usage (% by bytes)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(highestMax(keepLastValue(icarus.icaruspmt*.BoardReader.*.Fragment_Buffer_Full_%Bytes, 100), 10), 1)"
    }
   ]
  },
  {
   "title": "CRT Boardreaders: Top 10 Buffer Usage (% by bytes)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(highestMax(keepLastValue(icarus.crt*.BoardReader.*.Fragment_Buffer_Full_%Bytes, 100), 10), 1)"
    }
   ]
  },
  {
   "title": "Dispatcher Rates",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(keepLastValue(sumSeries(icarus.disp01.*.Input_Fragment_Rate), 100), 'Dispatcher Incoming Fragment Rate')"
    },
    {
     "target": "alias(keepLastValue(sumSeries(icarus.disp01.*.Event_Rate), 100), 'Dispatcher Processed Fragment Rate')"
    }
   ]
  }
 ]
}