{
 "title": "WR-TDC Monitor SPEC-TDC02",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "EVB04 Avg Event Building Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "sbnd.evb04.EventBuilder4.Average_Event_Building_Time"
    }
   ]
  },
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Run Number (P1)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition9.run_number" }
   ]
  },
  {
   "title": "TDC Monitor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 9 },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc02.BoardReader.55100.Fragment_Rate, 1), 'Artdaq Fragment  Rate')"
    },
    {
     "target": "alias(movingAverage(sbnd.tdc02.BoardReader.55100.Fragments_Sent, 1), 'TDC Fragment Rate')"
    }
   ]
  },
  {
   "title": "Collected Events Monitor",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "alias(keepLastValue(sbnd.tdc02.*.55100.Fragment_Count, 10), 'Fragments Sent from WR-TDC BoardReader')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.dl*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.disp*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in Dispatchers')"
    }
   ]
  },
  {
   "title": "Fragment Watcher",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(sbnd.evb*.EventBuilder*_art*.EventsWithEmptyFragments), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb*.EventBuilder*_art*.EventsWithMissingFragments), 3)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.evb*.EventBuilder*_art*.EventsProcessed), 3)"
    }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc02.BoardReader.55100.Fragment_Rate, 1), 4)"
    }
   ]
  },
  {
   "title": "TDC Sample Rate (all channels)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sbnd.tdc02.BoardReader.55100.TDC_Chan0_Sample_Rate, 'Chan0')"
    },
    {
     "target": "alias(sbnd.tdc02.BoardReader.55100.TDC_Chan1_Sample_Rate, 'Chan1')"
    },
    {
     "target": "alias(sbnd.tdc02.BoardReader.55100.TDC_Chan2_Sample_Rate, 'Chan2')"
    },
    {
     "target": "alias(sbnd.tdc02.BoardReader.55100.TDC_Chan3_Sample_Rate, 'Chan3')"
    },
    {
     "target": "alias(sbnd.tdc02.BoardReader.55100.TDC_Chan4_Sample_Rate, 'Chan4')"
    }
   ]
  },
  { "title": "WR TDC  Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "TDC Sample Rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Sample_Rate, 10), 4)"
    }
   ]
  },
  {
   "title": "Missed & Drained Samples",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Sample_Missed_Total, 10), 4)"
    },
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Sample_Drained_Total, 10), 4)"
    }
   ]
  },
  {
   "title": "Samples Total & Last Sequence",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Sample_Read_Total, 10), 4)"
    },
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Sample_Last_Sequence, 10), 4)"
    }
   ]
  },
  {
   "title": "WR Sync Status",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "alias(keepLastValue(sbnd.tdc02.BoardReader.55100.WR_Time_Synced, 10), 'WR')"
    }
   ]
  },
  {
   "title": "Request Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc02.BoardReader.55100.Request_Response_Time, 1), 4)"
    }
   ]
  },
  {
   "title": "SPEC Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc02.BoardReader.55100.SPEC_Temperature, 20), 4)"
    }
   ]
  },
  {
   "title": "TDC_Chan*_Timestamp_Gap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Timestamp_Gap, 4)"
    }
   ]
  },
  {
   "title": "EVB04 Avg Event Building Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sbnd.evb04.EventBuilder4.Average_Event_Building_Time"
    }
   ]
  },
  { "title": "Event Building", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "TDC Sample to Artdaq Fragment Time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc02.BoardReader.55100.Fragment_Create_Time_-_Average, 1), 'Avg')"
    },
    {
     "target": "alias(movingAverage(sbnd.tdc02.BoardReader.55100.Fragment_Create_Time_-_Max, 1), 'Max')"
    }
   ]
  },
  {
   "title": "Request Response Time",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc02.BoardReader.55100.Request_Response_Time, 1), 'RRT')"
    }
   ]
  },
  {
   "title": "BoardReader applyRequests() loop Avg Time",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc02.BoardReader.55100.Avg_Request_Response_Wait_Time, 1), 'APLY')"
    }
   ]
  },
  {
   "title": "%Buffer Full Fragments",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc02.BoardReader.55100.Fragment_Buffer_Full_%, 4)"
    }
   ]
  },
  {
   "title": "%Buffer Full Byte",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc02.BoardReader.55100.Fragment_Buffer_Full_%Bytes, 4)"
    }
   ]
  },
  { "title": "PoolBuffer Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Free Blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc02.BoardReader.55100.PoolBuffer_Free_Block_Count, 4)"
    }
   ]
  },
  {
   "title": "Fully Drained",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc02.BoardReader.55100.PoolBuffer_Fully_Drained_Count, 4)"
    }
   ]
  },
  {
   "title": "Low Watermark",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc02.BoardReader.55100.PoolBuffer_Low_Watermark, 4)"
    }
   ]
  },
  { "title": "WR TDC  Monitor Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "TDC Sample Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Sample_Rate, 1), 4)"
    }
   ]
  },
  {
   "title": "TDC Sample Time Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Sample_Time_Lag, 1), 4)"
    }
   ]
  },
  {
   "title": "TDC Sequence Gaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Sequence_Gap, 4)"
    }
   ]
  },
  {
   "title": "TDC Laggy Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc02.BoardReader.55100.TDC_Chan*_Laggy_Samples, 4)"
    }
   ]
  },
  {
   "title": "TDC Last Seen Sequence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc02.BoardReader.55100.TDC_Ch*_Sample_Last_Sequence, 4)"
    }
   ]
  },
  { "title": "Board Reader Core Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "BoardReader getNext() Avg Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc02.BoardReader.55100.Avg_Output_Wait_Time, 1), 4)"
    }
   ]
  },
  {
   "title": "Artdaq Fragment Buffer % Full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc02.BoardReader.55100.Fragment_Buffer_Full_%, 1), 4)"
    }
   ]
  },
  {
   "title": "BoardReader applyRequests() loop Avg Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(removeAboveValue(sbnd.tdc02.BoardReader.55100.Avg_Request_Response_Wait_Time, 0.5), 1), 4)"
    }
   ]
  },
  {
   "title": "BoardReader Fragments per getNext()",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc02.BoardReader.55100.Avg_Frags_Per_Read, 1), 4)"
    }
   ]
  },
  {
   "title": "BoardReader sendFragment() Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc02.BoardReader.55100.Avg_Output_Wait_Time, 1), 4)"
    }
   ]
  },
  {
   "title": "Board Reader Core Extra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frafments Per Non Empty Container",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
     "targets": [
      {
       "target": "alias(sbnd.tdc02.BoardReader.55100.Fragments_Per_Not_Empty_Container_-_Average, 'Avg')"
      },
      {
       "target": "alias(sbnd.tdc02.BoardReader.55100.Fragments_Per_Not_Empty_Container_-_Max, 'Max')"
      },
      {
       "target": "alias(sbnd.tdc02.BoardReader.55100.Fragments_Per_Not_Empty_Container_-_Min, 'Min')"
      }
     ]
    },
    {
     "title": "Frafments Per Non Empty Container",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 114 },
     "targets": [
      {
       "target": "alias(sbnd.tdc02.BoardReader.55100.Fragments_Per_Not_Empty_Container_-_Average, 'Avg')"
      },
      {
       "target": "alias(sbnd.tdc02.BoardReader.55099.Fragments_Per_Not_Empty_Container_-_Max, 'Max')"
      },
      {
       "target": "alias(sbnd.tdc02.BoardReader.55100.Fragments_Per_Not_Empty_Container_-_Min, 'Min')"
      }
     ]
    },
    {
     "title": "No data window around pull the request window",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "target": "aliasByNode(removeAboveValue(sbnd.tdc02.BoardReader.55100.No_Data_Window_Around_Request, 5000000000), 4)"
      },
      {
       "target": "aliasByNode(removeAboveValue(sbnd.tdc02.BoardReader.55099.No_Data_After_End_Window, 1000000000), 4)"
      },
      {
       "target": "aliasByNode(removeAboveValue(sbnd.tdc02.BoardReader.55100.No_Data_Before_Begin_Window, 1000000000), 4)"
      }
     ]
    },
    {
     "title": "Board Reader Core Request Monitor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 123 },
     "targets": [
      {
       "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.tdc02.BoardReader.55100.Requests_Yielding_Empty_Fragments, 1), 0.01), 4)"
      },
      {
       "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.tdc.BoardReader.55100.Requests_With_Missing_Data, 1), 0.01), 4)"
      },
      {
       "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.tdc02.BoardReader.55100.Requests_With_Window_Timeout, 1), 0.01), 4)"
      },
      {
       "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.*.BoardReader.55099.Fragment_Rate, 1), 0.01), 4)"
      }
     ]
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "/data Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sbnd.sbnd-evb01.data.Percent_Used, 'sbnd-evb01')"
    },
    {
     "target": "alias(sbnd.sbnd-evb02.data.Percent_Used, 'sbnd-evb02')"
    },
    {
     "target": "alias(sbnd.sbnd-evb03.data.Percent_Used, 'sbnd-evb03')"
    },
    {
     "target": "alias(sbnd.sbnd-evb04.data.Percent_Used, 'sbnd-evb04')"
    },
    {
     "target": "alias(sbnd.sbnd-evb05.data.Percent_Used, 'sbnd-evb05')"
    },
    {
     "target": "sbnd.sbnd-evb06.data.Percent_Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.BoardReader.55099.Process_CPU_Usage, 1), 4)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc.BoardReader.55099.Process_RAM_Usage, 4)"
    }
   ]
  }
 ]
}