{
 "title": "CAEN 1730 Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CAEN Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CAEN Temp",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "groupByNode(icarus.icaruspmt*.BoardReader.*.Channel*.Temp, 1, 'maxSeries')"
    }
   ]
  },
  {
   "title": "CAEN Running",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Running, 1)"
    }
   ]
  },
  {
   "title": "CAEN Busy",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Busy, 1)"
    }
   ]
  },
  {
   "title": "CAEN PLL",
   "type": "status-history",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.PLLLock, 1)"
    }
   ]
  },
  {
   "title": "CAEN Memory Full",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "target": "groupByNode(icarus.icaruspmt*.BoardReader.*.Channel*.MemoryFull, 1, 'sum')"
    }
   ]
  },
  {
   "title": "Event Buffer Fill %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.BoardBufferFillPercent, 1)"
    }
   ]
  },
  {
   "title": "Event Stored",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.BoardEventsStored, 1)"
    }
   ]
  },
  {
   "title": "Board Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.BoardEventRate, 1)"
    }
   ]
  },
  {
   "title": "Missing Board Events (gap)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Missing_Fragments, 1)"
    }
   ]
  },
  { "title": "Board Reader Core Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Data_Rate, 1)"
    }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Fragment_Rate, 1)"
    }
   ]
  },
  {
   "title": "Buffer Depth Fragments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Buffer_Depth_Fragments, 1)"
    }
   ]
  },
  {
   "title": "Fragment Buffer Full %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Fragment_Buffer_Full_%, 1)"
    }
   ]
  },
  {
   "title": "Request Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Request_Response_Time, 1)"
    }
   ]
  },
  {
   "title": "Average Fragment Size ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Average_Fragment_Size, 1)"
    }
   ]
  },
  {
   "title": "Fragment Creation Gap (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.FragmentCreationGapAvg, 1)"
    }
   ]
  },
  {
   "title": "Fragment Creation Gap (Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.FragmentCreationGapMax, 1)"
    }
   ]
  },
  {
   "title": "Laggy Fragments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Laggy_Fragments, 1)"
    }
   ]
  },
  {
   "title": "Missing Fragments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Missing_Fragments, 1)"
    }
   ]
  }
 ]
}