{
 "title": "ICARUS TPC BoardReaders, Detail",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Event Number",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "icarus.tpcew05.BoardReader.0.getNext.BoardEventNumber"
    }
   ]
  },
  {
   "title": "Running",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.Status.N_Running_-_Last"
    }
   ]
  },
  {
   "title": "TPC BoardReaders Busy",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.Status.N_Busy_-_Max"
    }
   ]
  },
  {
   "title": "GetData Fill Time, Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.GetData.FillTime_-_Average"
    }
   ]
  },
  {
   "title": "getNext Finish Time, Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.getNext.FinishTime_-_Average"
    }
   ]
  },
  {
   "title": "GetData ReturnTime, Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.GetData.ReturnTime_-_Average"
    }
   ]
  },
  {
   "title": "getNext Return Time, Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.getNext.ReturnTime_-_Average"
    }
   ]
  },
  {
   "title": "GetData, CircularBufferOccupany (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "icarus.tpc*.BoardReader.*.GetData.CircularBufferOccupancy_-_Average"
    }
   ]
  },
  {
   "title": "getNext, CircularBufferOccupancy (Average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.getNext.CircularBufferOccupancy_-_Average"
    }
   ]
  },
  {
   "title": "Event Number btw Board Diff",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.MaxBoardEventNumDiff_-_Max"
    }
   ]
  }
 ]
}