{
 "title": "PTB Monitor",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Run Number (P 3)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition3.run_number" }
   ]
  },
  {
   "title": "Overall Trigger Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "target": "sbnd.ptb.BoardReader.8.PTB_HLT_rate"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "targets": [
    {
     "target": "sbnd.ptb.BoardReader.8.Data_Rate"
    }
   ]
  },
  {
   "title": "PTB Word Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 1 },
   "targets": [
    {
     "target": "sbnd.ptb.BoardReader.8.PTB_Word_rate"
    }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 1 },
   "targets": [
    {
     "target": "sbnd.ptb.BoardReader.8.Fragment_Rate"
    }
   ]
  },
  {
   "title": "PTB Trigger Rates 999 (old artdaq)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "PTB HLT Rates",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias(sbnd.ptb.BoardReader.999.PTB_HLT_rate, 'Total HLT Rate')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.999.PTB_HLT_0_rate, 'HLT 0')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.999.PTB_HLT_1_rate, 'HLT 1')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.999.PTB_HLT_2_rate, 'HLT 2')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.999.PTB_HLT_3_rate, 'HLT 3')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.999.PTB_HLT_4_rate, 'HLT 4')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.999.PTB_HLT_5_rate, 'HLT 5')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.999.PTB_HLT_6_rate, 'HLT 6')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.999.PTB_HLT_7_rate, 'HLT 7')"
      }
     ]
    },
    {
     "title": "PTB Fragment Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "target": "sbnd.ptb.BoardReader.*.Fragment_Rate"
      }
     ]
    },
    {
     "title": "PTB LLT Rates",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "target": "alias(movingAverage(sbnd.ptb.BoardReader.*.PTB_LLT_rate, 1), 'Total LLT Rate')"
      },
      {
       "target": "alias(movingAverage(sbnd.ptb.BoardReader.*.PTB_LLT_11_rate, 1), 'LLT 11')"
      },
      {
       "target": "alias(movingAverage(sbnd.ptb.BoardReader.*.PTB_LLT_14_rate, 1), 'LLT 14')"
      },
      {
       "target": "alias(movingAverage(sbnd.ptb.BoardReader.*.PTB_LLT_17_rate, 1), 'LLT 17')"
      },
      {
       "target": "alias(movingAverage(sbnd.ptb.BoardReader.*.PTB_LLT_27_rate, 1), 'LLT 27')"
      },
      {
       "target": "alias(movingAverage(sbnd.ptb.BoardReader.*.PTB_LLT_28_rate, 1), 'LLT 28')"
      },
      {
       "target": "alias(movingAverage(sbnd.ptb.BoardReader.*.PTB_LLT_29_rate, 1), 'LLT 29')"
      },
      {
       "target": "alias(movingAverage(sbnd.ptb.BoardReader.*.PTB_LLT_30_rate, 1), 'LLT 30')"
      },
      {
       "target": "alias(movingAverage(sbnd.ptb.BoardReader.*.PTB_LLT_31_rate, 1), 'LLT 31')"
      }
     ]
    }
   ]
  },
  {
   "title": "PTB Trigger Rates 8 (new artdaq)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "PTB HLT Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_rate, 'Total HLT Rate')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_0_rate, 'HLT 0 (random 1)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_1_rate, 'HLT 1 (BNB 0 bias)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_2_rate, 'HLT 2 (BNB light+beam)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_3_rate, 'HLT 3 (off-beam 0 bias)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_4_rate, 'HLT 4 (off-beam light+beam)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_6_rate, 'HLT 6  (Light)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_7_rate, 'HLT 7 (CRT north&bottom)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_8_rate, 'HLT 8 (CRT north&east)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_9_rate, 'HLT 9 (CRT west&east)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_10_rate, 'HLT 10 (CRT west&north)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_11_rate, 'HLT 11 (CRT south&west)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_12_rate, 'HLT 12 (CRT south&east)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_13_rate, 'HLT 13 (CRT south&north)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_14_rate, 'HLT 14 (CRT south&north only)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_15_rate, 'HLT 15 (CRT west&east only)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_16_rate, 'HLT 16 (muDAR)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_17_rate, 'HLT 17 (muDAR off-beam)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_19_rate, 'HLT 19 (Sunset)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_20_rate, 'HLT 20 (BNB CRT reset)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_21_rate, 'HLT 21 (off-beam CRT reset)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_22_rate, 'HLT 22 (uninhibited HLT 4)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_23_rate, 'HLT 23 (uninhibited HLT 17)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_26_rate, 'HLT 26 (Beam acceptance)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_27_rate, 'HLT 27 (Off-Beam acceptance)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_28_rate, 'HLT 28 (light+prearrival)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_29_rate, 'HLT 29 (light + post ET)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_30_rate, 'HLT 30 (light+off-beam prearrival)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_HLT_31_rate, 'HLT 31 (random 2)')"
    }
   ]
  },
  {
   "title": "PTB Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "target": "sbnd.ptb.BoardReader.*.Fragment_Rate"
    }
   ]
  },
  {
   "title": "PTB LLT Rates",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_rate, 'Total LLT Rate')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_0_rate, 'LLT 0 (Post ET Flash)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_1_rate, 'LLT 1 (Post ET Inhibit)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_2_rate, 'LLT 2 (Rand 1)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_3_rate, 'LLT 3 (Rand 2)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_4_rate, 'LLT 4 (CRT Reset)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_5_rate, 'LLT 5 (CRT Reset EXT)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_6_rate, 'LLT 6 (CRT all)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_7_rate, 'LLT 7 (CRT top high)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_8_rate, 'LLT 8 (CRT east)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_9_rate, 'LLT 9 (CRT south)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_10_rate, 'LLT 10 (CRT bottom)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_11_rate, 'LLT 11 (CRT top low)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_12_rate, 'LLT 12 (CRT north)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_13_rate, 'LLT 13 (CRT west)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_14_rate, 'LLT 14 (MTCA)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_15_rate, 'LLT 15 (CAEN IN 10)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_16_rate, 'LLT 16')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_17_rate, 'LLT 17 (Any Majority)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_18_rate, 'LLT 18 (MTC/A low)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_19_rate, 'LLT 19')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_20_rate, 'LLT 20 (MTC/A hi)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_21_rate, 'LLT 21 (MTC/A med)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_22_rate, 'LLT 22')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_23_rate, 'LLT 23')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_24_rate, 'LLT 24 (Off-Beam EW)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_25_rate, 'LLT 25 (Off-Beam Pre A)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_26_rate, 'LLT 26 (Off-Beam Beam Acc)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_27_rate, 'LLT 27 (Off-Beam Post A)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_28_rate, 'LLT 28 (EW)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_29_rate, 'LLT 29 (Pre A)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_30_rate, 'LLT 30 (Beam Acc)')"
    },
    {
     "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_31_rate, 'LLT 31 (Post A)')"
    }
   ]
  },
  {
   "title": "PTB LLT Rates Detail (8)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "PTB LLT Rates",
     "type": "gauge",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_rate, 'Total LLT Rate')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_0_rate, 'LLT 0')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_1_rate, 'LLT 1')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_2_rate, 'LLT 2')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_3_rate, 'LLT 3')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_4_rate, 'LLT 4')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_5_rate, 'LLT 5')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_6_rate, 'LLT 6')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_7_rate, 'LLT 7')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_8_rate, 'LLT 8')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_9_rate, 'LLT 9')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_10_rate, 'LLT 10')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_11_rate, 'LLT 11')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_12_rate, 'LLT 12')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_13_rate, 'LLT 13')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_14_rate, 'LLT 14')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_15_rate, 'LLT 15')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_16_rate, 'LLT 16')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_17_rate, 'LLT 17')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_18_rate, 'LLT 18')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_23_rate, 'LLT 23')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_24_rate, 'LLT 24')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_25_rate, 'LLT 25')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_26_rate, 'LLT 26')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_27_rate, 'LLT 27')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_28_rate, 'LLT 28')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_29_rate, 'LLT 29')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_30_rate, 'LLT 30')"
      },
      {
       "target": "alias(sbnd.ptb.BoardReader.8.PTB_LLT_31_rate, 'LLT 31')"
      }
     ]
    }
   ]
  },
  { "title": "PTB Fragments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "PTB Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 34 },
   "targets": [
    {
     "target": "sbnd.ptb.BoardReader.*.Fragment_Rate"
    }
   ]
  },
  {
   "title": "Cumulative Fragments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 34 },
   "targets": [
    {
     "target": "aliasByMetric(sbnd.ptb.BoardReader.8.PTB_Fragments_Sent)"
    },
    {
     "target": "aliasByMetric(sbnd.ptb.BoardReader.8.Fragment_Count)"
    },
    { "target": "sbnd.ptb.BoardReader.999" }
   ]
  },
  {
   "title": "Fragment Buffer Full %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sbnd.ptb.BoardReader.8.Fragment_Buffer_Full_%"
    }
   ]
  },
  {
   "title": "Average Fragments/Read",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "target": "sbnd.ptb.BoardReader.8.Avg_Frags_Per_Read"
    }
   ]
  },
  {
   "title": "Average Fragment Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 42 },
   "targets": [
    {
     "target": "aliasByMetric(sbnd.ptb.BoardReader.8.Average_Fragment_Size)"
    }
   ]
  },
  {
   "title": "Fragment Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 42 },
   "targets": [
    {
     "target": "aliasByMetric(sbnd.ptb.BoardReader.8.Fragment_Latency_at_Send_-_Average)"
    },
    {
     "target": "aliasByMetric(sbnd.ptb.BoardReader.8.Fragment_Latency_at_Send_-_Max)"
    }
   ]
  }
 ]
}