{
 "title": "ICARUS TPC Board Temperatures",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TPC WW Board Temp1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "icarus.tpcww*.BoardReader.*.Temp.Board*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW Board Temp2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "icarus.tpcww*.BoardReader.*.Temp.Board*.Temp2"
    }
   ]
  },
  {
   "title": "TPC WE Board Temp1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "icarus.tpcwe*.BoardReader.*.Temp.Board*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE Board Temp2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "icarus.tpcwe*.BoardReader.*.Temp.Board*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE Board Temp1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "icarus.tpcee*.BoardReader.*.Temp.Board*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE Board Temp2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "icarus.tpcee*.BoardReader.*.Temp.Board*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EW Board Temp1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "icarus.tpcew*.BoardReader.*.Temp.Board*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW Board Temp2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "icarus.tpcew*.BoardReader.*.Temp.Board*.Temp2"
    }
   ]
  }
 ]
}