{
 "title": "TPC Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "NTB Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "sbnd.ntb*.BoardReader.*.Fragment_Rate"
    }
   ]
  },
  {
   "title": "EVB Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "currentAbove(sbnd.evb0*.EventBuilder*.Data_Rate, -1)"
    }
   ]
  },
  {
   "title": "TPC01 Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "sbnd.tpc01.BoardReader.*.Fragment_Rate"
    }
   ]
  },
  {
   "title": "TPC01 BufferCapacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "sbnd.tpc01.BoardReader.*.Fragment_Buffer_Full_%"
    }
   ]
  },
  {
   "title": "TPC01 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "sbnd.tpc01.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC02 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "sbnd.tpc02.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC03 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "sbnd.tpc03.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC04 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "target": "sbnd.tpc04.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC05 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "target": "sbnd.tpc05.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC06 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "target": "sbnd.tpc06.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC07 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "target": "sbnd.tpc07.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC08 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "target": "sbnd.tpc08.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC09 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "target": "sbnd.tpc09.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC10 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "target": "sbnd.tpc10.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "TPC11 Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "target": "sbnd.tpc11.BoardReader.*.Data_Rate"
    }
   ]
  }
 ]
}