{
 "title": "WR-TDC Artdaq Driver",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Run Number (P 6)", "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "TDC Monitor",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc.artdaqDriver.Event_Rate, 1), 'Artdaq Fragment  Rate')"
    },
    {
     "target": "alias(movingAverage(sbnd.tdc.artdaqDriver.Fragments_Sent, 1), 'TDC Fragment Rate')"
    }
   ]
  },
  {
   "title": "Collected Events Monitor",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "alias(sbnd.tdc.artdaqDriver.Events_Released_to_art_this_run, 'Events Released to art in EventBuilders')"
    }
   ]
  },
  {
   "title": "TDC Sample Rate (all channels)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sumSeries(sbnd.tdc.artdaqDriver.TDC_Chan*_Sample_Rate, *), 1), 3)"
    }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.artdaqDriver.Event_Rate, 1), 3)"
    }
   ]
  },
  { "title": "WR TDC  Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "TDC Sample Rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.artdaqDriver.TDC_Chan*_Sample_Rate, 10), 3)"
    }
   ]
  },
  {
   "title": "Missed & Drained Samples",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.artdaqDriver.TDC_Chan*_Sample_Missed_Total, 10), 3)"
    },
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.artdaqDriver.TDC_Chan*_Sample_Drained_Total, 10), 3)"
    }
   ]
  },
  {
   "title": "Samples Total & Last Sequence",
   "type": "table",
   "gridPos": { "h": 13, "w": 5, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.artdaqDriver.TDC_Chan*_Sample_Read_Total, 10), 3)"
    },
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.artdaqDriver.TDC_Chan*_Sample_Last_Sequence, 10), 3)"
    }
   ]
  },
  {
   "title": "WR Sync Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "alias(keepLastValue(sbnd.tdc.artdaqDriver.WR_Time_Synced, 10), 'WR')"
    }
   ]
  },
  {
   "title": "Average Event Building Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.artdaqDriver.Average_Event_Building_Time, 1), 3)"
    }
   ]
  },
  {
   "title": "SPEC Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.artdaqDriver.SPEC_Temperature, 10), 3)"
    }
   ]
  },
  { "title": "Event Building", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "TDC Sample to Artdaq Fragment Time",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc.artdaqDriver.Fragment_Create_Time_-_Average, 1), 'Avg')"
    },
    {
     "target": "alias(movingAverage(sbnd.tdc.artdaqDriver.Fragment_Create_Time_-_Max, 1), 'Max')"
    }
   ]
  },
  {
   "title": "EVB  Full Buffers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.artdaqDriver.Shared_Memory_Full_Buffers, 1), 2)"
    }
   ]
  },
  {
   "title": "TDC Sample Rates",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasSub(movingAverage(sbnd.tdc.artdaqDriver.TDC_Chan*_Sample_Rate, 1), '.*Chan(\\d+).*', '\\1')"
    }
   ]
  },
  {
   "title": "EVB Memory % Full",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.artdaqDriver.Shared_Memory_Full_%, 1), 3)"
    }
   ]
  },
  {
   "title": "EVB Memory Full %",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(keepLastValue(sbnd.tdc.artdaqDriver.Shared_Memory_Full_%, 10), '1')"
    }
   ]
  },
  {
   "title": "EVB  Pending Buffers",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "target": "alias(movingAverage(sbnd.tdc.artdaqDriver.Shared_Memory_Pending_Buffers, 1), '1')"
    }
   ]
  },
  { "title": "PoolBuffer Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Free Blocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc.artdaqDriver.PoolBuffer_Free_Block_Count, 3)"
    }
   ]
  },
  {
   "title": "Fully Drained",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc.artdaqDriver.PoolBuffer_Fully_Drained_Count, 3)"
    }
   ]
  },
  {
   "title": "Low Watermark",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.artdaqDriver.PoolBuffer_Low_Watermark, 1), 3)"
    }
   ]
  },
  { "title": "WR TDC  Monitor Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "TDC Sample Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(movingAverage(sbnd.tdc.artdaqDriver.TDC_Chan*_Sample_Rate, 1), 0.001), 3)"
    }
   ]
  },
  {
   "title": "TDC Sample Time Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.artdaqDriver.TDC_Chan*_Sample_Time_Lag, 1), 3)"
    }
   ]
  },
  {
   "title": "TDC Sequence Gaps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc.artdaqDriver.TDC_Chan*_Sequence_Gap,3 )"
    }
   ]
  },
  {
   "title": "TDC Laggy Samples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.tdc.artdaqDriver.TDC_Chan*_Laggy_Samples, 3)"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.artdaqDriver.Process_CPU_Usage, 1), 3)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.tdc.artdaqDriver.Process_RAM_Usage, 1), 3)"
    }
   ]
  }
 ]
}