{
 "title": "artdaq Dispatcher",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "RATES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rates",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "icarus.disp01.Dispatcher1.Event_Rate"
    },
    {}
   ]
  },
  {
   "title": "Event Rate",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Event_Rate)"
    },
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Input_Fragment_Rate)"
    }
   ]
  },
  { "title": "SHARED MEMORY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Shared Memory [%]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Available_%)"
    },
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Full_%)"
    }
   ]
  },
  {
   "title": "Shared Memory [%]",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Available_%)"
    },
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Full_%)"
    }
   ]
  },
  {
   "title": "Shared Memory Buffers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 29 },
   "targets": [
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Available_Buffers)"
    },
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Pending_Buffers)"
    },
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Reading_Buffers)"
    },
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Full_Buffers)"
    }
   ]
  },
  {
   "title": "Shared Memory Buffers",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Available_Buffers)"
    },
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Pending_Buffers)"
    },
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Reading_Buffers)"
    },
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Shared_Memory_Full_Buffers)"
    }
   ]
  },
  { "title": "BACK-PRESSURE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Back-pressure wait time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "target": "aliasByMetric(icarus.disp01.Dispatcher1.Back-pressure_wait_time)"
    }
   ]
  }
 ]
}