{
 "title": "X-ARAPUCA Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Rates Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Run Number (P 6)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition5.run_number" }
   ]
  },
  {
   "title": "X-ARAPUCA Artdaq Fragment Rate",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.*.BoardReader.{41223,41229,41232,41235}.Fragment_Rate, 10), 1)"
    }
   ]
  },
  { "title": "TDC Sample Rate", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 } },
  {
   "title": "PTB Overall Trigger Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 5 },
   "targets": [
    {
     "target": "sbnd.ptb.BoardReader.999.PTB_HLT_rate"
    }
   ]
  },
  {
   "title": "X-ARAPUCA Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.xarapuca0*.BoardReader.{41223,41229,41232,41235}.Fragment_Rate, 1, 2, 3)"
    }
   ]
  },
  { "title": "Empty Fragments", "gridPos": { "h": 10, "w": 5, "x": 10, "y": 12 } },
  { "title": "Missing Fragments", "gridPos": { "h": 10, "w": 5, "x": 15, "y": 12 } },
  { "title": "Fragment Watcher", "gridPos": { "h": 10, "w": 4, "x": 20, "y": 12 } },
  { "title": "Data and Memory Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Fragment Buffer %",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.xarapuca0*.BoardReader.{41223,41229,41232,41235}.Fragment_Buffer_Full_%Fragments, 1)"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "sbnd.xarapuca0*.BoardReader.{41223,41229,41232,41235}.Data_Rate"
    }
   ]
  },
  {
   "title": "Request Response Time",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.xarapuca0*.BoardReader.{41223,41229,41232,41235}.Request_Response_Time, 1), 1)"
    }
   ]
  },
  {
   "title": "Average Fragment Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "sbnd.xarapuca0*.BoardReader.{41223,41229,41232,41235}.Average_Fragment_Size"
    }
   ]
  },
  { "title": "Event Builder Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "EVB  Pending Buffers",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 34 },
   "targets": [
    {
     "target": "aliasByNode(sortByName(movingAverage(sbnd.evb*.EventBuilder*.Shared_Memory_Pending_Buffers, 1), true), 2)"
    }
   ]
  },
  { "title": "EVB  Pending Buffers", "gridPos": { "h": 7, "w": 13, "x": 11, "y": 34 } },
  {
   "title": "EVB Memory Full %",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "sortByName(aliasByNode(keepLastValue(sbnd.evb*.EventBuilder*.Shared_Memory_Full_%, 10), 2), true)"
    }
   ]
  },
  { "title": "EVB  Full Buffers", "gridPos": { "h": 7, "w": 13, "x": 11, "y": 41 } },
  {
   "title": "Channel Status Monitoring ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": " Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 49 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.*.*.CAENV1730.Card3.*.Status, 1, 6)"
      }
     ]
    },
    {
     "title": " Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 49 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.*.*.CAENV1730.Card5.*.Status, 1, 6)"
      }
     ]
    },
    {
     "title": " Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 49 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.*.*.CAENV1730.Card7.*.Status, 1, 6)"
      }
     ]
    },
    {
     "title": " Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 5, "x": 15, "y": 49 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.*.*.CAENV1730.Card9.*.Status, 1, 6)"
      }
     ]
    },
    {
     "title": " Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 49 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.*.*.CAENV1730.Card11.*.Status, 1, 6)"
      }
     ]
    },
    {
     "title": " Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 57 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.*.*.CAENV1730.Card13.*.Status, 1, 6)"
      }
     ]
    },
    {
     "title": " Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 57 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.*.*.CAENV1730.Card15.*.Status, 1, 6)"
      }
     ]
    },
    {
     "title": " Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 57 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.*.*.CAENV1730.Card17.*.Status, 1, 6)"
      }
     ]
    },
    {
     "title": " Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 57 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.*.*.CAENV1730.Card19.*.Status, 1, 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Channel Memory Full %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Full %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 50 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.BoardReader.*.CAENV1730.Card3.*.MemoryFull, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory Full %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 50 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.BoardReader.*.CAENV1730.Card5.*.MemoryFull, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory Full %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 50 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.BoardReader.*.CAENV1730.Card7.*.MemoryFull, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory Full %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 50 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.BoardReader.*.CAENV1730.Card9.*.MemoryFull, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory Full %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 50 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.BoardReader.*.CAENV1730.Card11.*.MemoryFull, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory Full %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 57 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.BoardReader.*.CAENV1730.Card13.*.MemoryFull, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory Full %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 57 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.BoardReader.*.CAENV1730.Card15.*.MemoryFull, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory Full %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 57 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.BoardReader.*.CAENV1730.Card17.*.MemoryFull, 1, 6)"
      }
     ]
    },
    {
     "title": "Memory Full %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 57 },
     "targets": [
      {
       "target": "aliasByNode(sbnd.pmtx0*.BoardReader.*.CAENV1730.Card19.*.MemoryFull, 1, 6)"
      }
     ]
    }
   ]
  }
 ]
}