{
 "title": "PMT Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Rates Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Run Number (P 6)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sbnd.partition1.run_number" }
   ]
  },
  {
   "title": "PMT Artdaq Fragment Rate",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(movingAverage(sbnd.pmt*.BoardReader.*.Fragment_Rate, 10), 1), -1)"
    }
   ]
  },
  {
   "title": "TDC Sample Rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(keepLastValue(sbnd.tdc.BoardReader.55099.TDC_Chan*_Sample_Rate, 10), 4)"
    }
   ]
  },
  {
   "title": "PTB Overall Trigger Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 5 },
   "targets": [
    {
     "target": "currentAbove(sbnd.ptb.BoardReader.*.PTB_HLT_rate, -1)"
    }
   ]
  },
  {
   "title": "PMT Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt0*.BoardReader.4096*.Fragment_Rate, 1, 2, 3)"
    }
   ]
  },
  {
   "title": "Missing/Empty fragments",
   "type": "stat",
   "description": "Number of events with mising fragments",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.Events_Released_to_art_this_run, 10)), 'Total Events')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.EventsWithEmptyFragments, 10)), 'Events wth empty fragments')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(sbnd.evb*.*.EventsWithMissingFragments, 10)), 'Events with missing fragments')"
    }
   ]
  },
  { "title": "Data and Memory Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Fragment Buffer %",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "currentAbove(aliasByNode(sbnd.pmt*.BoardReader.*.Fragment_Buffer_Full_%Fragments, 1), -1)"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "sbnd.pmt0*.BoardReader.*.Data_Rate"
    }
   ]
  },
  {
   "title": "Request Response Time",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(sbnd.pmt0*.BoardReader.4096*.Request_Response_Time, 1), 1)"
    }
   ]
  },
  {
   "title": "Average Fragment Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "sbnd.pmt0*.BoardReader.*.Average_Fragment_Size"
    }
   ]
  },
  { "title": "Channel Temperature Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Temperature - Fragment ID 40960",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt00.*.40960.Channel*.Temp, 4)"
    }
   ]
  },
  {
   "title": "Temperature - Fragment ID 40961",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt00.*.40961.Channel*.Temp, 4)"
    }
   ]
  },
  {
   "title": "Temperature - Fragment ID 40962",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt00.*.40962.Channel*.Temp, 4)"
    }
   ]
  },
  {
   "title": "Temperature - Fragment ID 40963",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt00.*.40963.Channel*.Temp, 4)"
    }
   ]
  },
  {
   "title": "Temperature - Fragment ID 40964",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt00.*.40964.Channel*.Temp, 4)"
    }
   ]
  },
  {
   "title": "Temperature - Fragment ID 40965",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt00.*.40965.Channel*.Temp, 4)"
    }
   ]
  },
  {
   "title": "Temperature - Fragment ID 40966",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt00.*.40966.Channel*.Temp, 4)"
    }
   ]
  },
  {
   "title": "Temperature - Fragment 40967",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt00.*.40967.Channel*.Temp, 4)"
    }
   ]
  },
  {
   "title": "Temperature - Fragment ID 40968",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(sbnd.pmt09.*.40968.Channel*.Temp, 4)"
    }
   ]
  }
 ]
}