{
 "title": "WR Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Trigger Rates",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.EventRate, 10), 0), 'Total')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.BNBEventRate, 10), 0), 'BNB')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.NuMIEventRate, 10), 0), 'NuMI')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.BNBOffbeamEventRate, 10), 0), 'BNBOffBeam')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.NuMIOffbeamEventRate, 10), 0), 'NuMIOffBeam')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.OtherEventRate, 10), 0), 'Other')"
    }
   ]
  },
  {
   "title": "Trigger Rates",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.EventRate, 10), 0), 'Total')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.BNBEventRate, 10), 0), 'BNB')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.NuMIEventRate, 10), 0), 'NuMI')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.BNBOffbeamEventRate, 10), 0), 'BNBOffBeam')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.NuMIOffbeamEventRate, 10), 0), 'NuMIOffBeam')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.OtherEventRate, 10), 0), 'Other')"
    }
   ]
  },
  {
   "title": "Beam Signals ",
   "type": "gauge",
   "description": "Rate of the beam signals transmitted through the White Rabbit network",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(icarus.daq02.*.*.WR_CLK02_SPEC_DIO_gatedBES.DIO_Channel_4_Rates, 'BNB Gated BES')"
    },
    {
     "target": "alias(icarus.daq02.*.*.WR_CLK02_SPEC_DIO_$1D.DIO_Channel_1_Rates, 'BNB $1D')"
    },
    {
     "target": "alias(icarus.daq02.BoardReader.*.WR_CLK02_SPEC_DIO_$74.DIO_Channel_3_Rates, 'NuMI MIBS $74')"
    },
    {
     "target": "alias(averageSeries(icarus.daq02.BoardReader.*.WR_CLK02_SPEC_DIO_$AE.DIO_Channel_2_Rates), 'NuMI $AD')"
    },
    {
     "target": "alias(averageSeries(icarus.daq02.BoardReader.*.WR_CLK02_SPEC_DIO_PPS.DIO_Channel_0_Rates), 'PPS')"
    }
   ]
  },
  {
   "title": "WR Rates",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 23 },
   "targets": [
    {
     "target": "icarus.daq02.BoardReader.*.WR_*.DIO_*_Rates"
    }
   ]
  }
 ]
}