{
 "title": "DAQ Performance Monitor",
 "description": "https://github.com/art-daq/artdaq/wiki/Artdaq-built-in-metric-catalog",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BoardReader Data Rate",
   "type": "stat",
   "description": "Total Data Rate from a Board Reader Subsystem",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(sumSeries(sbnd.crt*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.pmt*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.tpc*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.ntb*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.ptb*.BoardReader.*.Data_Rate), 1)"
    },
    {
     "target": "aliasByNode(sumSeries(sbnd.tdc*.BoardReader.*.Data_Rate), 1)"
    }
   ]
  },
  {
   "title": "Data_Rate (stacked)",
   "type": "timeseries",
   "description": "Data rate by subsystem -- stacked",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.crt*.BoardReader.*.Data_Rate), 'CRT')"
    },
    {
     "target": "alias(sumSeries(sbnd.tpc*.BoardReader.*.Data_Rate), 'TPC')"
    },
    {
     "target": "alias(sumSeries(sbnd.ntb*.BoardReader.*.Data_Rate), 'NTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.pmt00.BoardReader.*.Data_Rate), 'PMT')"
    },
    {
     "target": "alias(sumSeries(sbnd.ptb*.BoardReader.*.Data_Rate), 'PTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.Data_Rate), 'SPEC TDC')"
    },
    {
     "target": "alias(sumSeries(sbnd.xarapuca*.BoardReader.*.Data_Rate), 'XARAPUCA')"
    }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "timeseries",
   "description": "Fragment Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.*.BoardReader.*.Fragment_Rate), 'Total')"
    },
    {
     "target": "alias(sumSeries(sbnd.pmt*.BoardReader.*.Fragment_Rate), 'PMT')"
    },
    {
     "target": "alias(sumSeries(sbnd.crt*.BoardReader.*.Fragment_Rate), 'CRT')"
    },
    {
     "target": "alias(sumSeries(sbnd.tpc*.BoardReader.*.Fragment_Rate), 'TPC')"
    },
    {
     "target": "alias(sumSeries(sbnd.ntb*.BoardReader.*.Fragment_Rate), 'NTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.ptb*.BoardReader.*.Fragment_Rate), 'PTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc*.BoardReader.*.Fragment_Rate), 'TDC')"
    },
    {
     "target": "alias(sumSeries(sbnd.xarapuca*.BoardReader.*.Fragment_Rate), 'ARAPUCA')"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*.Incomplete_Event_Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.evb*.EventBuilder*.Event_Rate), 'Total Event Rate')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb*.EventBuilder*.Incomplete_Event_Rate), 'Incomplete Event Rate')"
    }
   ]
  },
  {
   "title": "EventBuilder*.Average_Event_Size",
   "type": "timeseries",
   "description": "EventBuilder*.Average_Event_Size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sbnd.*.EventBuilder*.Average_Event_Size"
    }
   ]
  },
  {
   "title": "EventBuilder*_art*.EventsWithMissingFragments",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*_art*.EventsWithMissingFragments",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.evb01.EventBuilder*_art*.EventsWithMissingFragments), 'evb01')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb02.EventBuilder*_art*.EventsWithMissingFragments), 'evb02')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb03.EventBuilder*_art*.EventsWithMissingFragments), 'evb03')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb04.EventBuilder*_art*.EventsWithMissingFragments), 'evb04')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb05.EventBuilder*_art*.EventsWithMissingFragments), 'evb05')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb06.EventBuilder*_art*.EventsWithMissingFragments), 'evb06')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb07.EventBuilder*_art*.EventsWithMissingFragments), 'evb07')"
    }
   ]
  },
  {
   "title": "EventBuilder*_art*.EventsWithEmptyFragments",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*_art*.EventsWithEmptyFragments",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "sbnd.evb*.EventBuilder*_art*.EventsWithEmptyFragments"
    },
    {
     "target": "alias(sumSeries(sbnd.evb*.EventBuilder*_art*.EventsWithEmptyFragments), 'Total')"
    }
   ]
  },
  { "title": "Buffer Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "BoardReader.*.Fragment_Buffer_Full_%",
   "type": "timeseries",
   "description": "sbnd.*.BoardReader.*.Fragment_Buffer_Full_%",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(sbnd.tpc*.BoardReader.*.Fragment_Buffer_Full_%, 'TPC')"
    },
    {
     "target": "alias(sbnd.crt*.BoardReader.*.Fragment_Buffer_Full_%, 'CRT')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.*.Fragment_Buffer_Full_%, 'PMT')"
    },
    {
     "target": "alias(sbnd.ntb*.BoardReader.*.Fragment_Buffer_Full_%, 'NTB')"
    },
    {
     "target": "alias(sbnd.xarapuca*.BoardReader.*.Fragment_Buffer_Full_%, 'XA')"
    },
    {
     "target": "alias(sbnd.tdc*.BoardReader.*.Fragment_Buffer_Full_%, 'SPEC-TDC')"
    }
   ]
  },
  {
   "title": "EventBuilder*.Shared_Memory_Full_%",
   "type": "timeseries",
   "description": "sbnd.*.EventBuilder*.Shared_Memory_Full_%",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "sbnd.*.EventBuilder*.Shared_Memory_Full_%"
    }
   ]
  },
  {
   "title": "EventBuilder*.Shared_Memory_Available_Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "target": "aliasByNode(currentAbove(sbnd.evb01.EventBuilder*.Shared_Memory_Available_Buffers, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb02.EventBuilder*.Shared_Memory_Available_Buffers, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb03.EventBuilder*.Shared_Memory_Available_Buffers, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb04.EventBuilder*.Shared_Memory_Available_Buffers, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb05.EventBuilder*.Shared_Memory_Available_Buffers, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb06.EventBuilder*.Shared_Memory_Available_Buffers, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb07.EventBuilder*.Shared_Memory_Available_Buffers, -1), 2)"
    }
   ]
  },
  {
   "title": "EventBuilder*.Shared_Memory_Pending_Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "target": "sbnd.evb*.*.Shared_Memory_Pending_Buffers"
    }
   ]
  },
  {
   "title": "Dispatcher*.Shared_Memory_Available_Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "target": "sbnd.disp*.*.Shared_Memory_Available_Buffers"
    }
   ]
  },
  {
   "title": "Dispatcher*.Shared_Memory_Pending_Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "target": "sbnd.disp*.*.Shared_Memory_Pending_Buffers"
    }
   ]
  },
  { "title": "Event Building Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "EventBuilder*.Back-pressure_wait_time",
   "type": "timeseries",
   "description": "sbnd.evb0*.EventBuilder*.Back-pressure_wait_time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "target": "sbnd.evb*.EventBuilder*.Back-pressure_wait_time"
    }
   ]
  },
  {
   "title": "EventBuilder*.Average_Event_Building_Time",
   "type": "timeseries",
   "description": "sbnd.*.EventBuilder*.Average_Event_Building_Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sbnd.*.EventBuilder*.Average_Event_Building_Time"
    }
   ]
  },
  {
   "title": "EventBuilder*.Average Input Wait Time",
   "type": "timeseries",
   "description": "Fragment latency at send- max  \n(max series where there is more then one)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sbnd.evb*.*.Avg_Input_Wait_Time"
    }
   ]
  },
  {
   "title": "EventBuilder*.ArtdaqInputHelper_Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "currentAbove(sbnd.*.EventBuilder*.ArtdaqInputHelper_Latency, -1)"
    }
   ]
  },
  {
   "title": "EventBuilder*.Average Processing Time ",
   "type": "timeseries",
   "description": "Fragment latency at send- max  \n(max series where there is more then one)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sbnd.evb*.*.Avg_Processing_Time"
    }
   ]
  },
  {
   "title": "Fragment_Rate (stacked)",
   "type": "timeseries",
   "description": "Fragment rate by subsystem -- stacked",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.crt*.BoardReader.*.Fragment_Rate), 'CRT')"
    },
    {
     "target": "alias(sumSeries(sbnd.ntb*.BoardReader.*.Fragment_Rate), 'NTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.pmt*.BoardReader.*.Fragment_Rate), 'PMT')"
    },
    {
     "target": "alias(sumSeries(sbnd.ptb*.BoardReader.*.Fragment_Rate), 'PTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.Fragment_Rate), 'SPEC TDC')"
    },
    {
     "target": "alias(sumSeries(sbnd.tpc*.BoardReader.*.Fragment_Rate), 'TPC')"
    }
   ]
  },
  {
   "title": "EventBuilder*.Average Read Time ",
   "type": "timeseries",
   "description": "Fragment latency at send- max  \n(max series where there is more then one)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "target": "sbnd.evb*.*.Avg_Read_Time" }
   ]
  },
  { "title": "Send/Receive Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Fragement latency max",
   "type": "timeseries",
   "description": "Fragment latency at send- max  \n(max series where there is more then one)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "alias(maxSeries(sbnd.crt*.BoardReader.*.Fragment_Latency_at_Send_-_Max), 'CRT')"
    },
    {
     "target": "alias(maxSeries(sbnd.ntb*.BoardReader.*.Fragment_Latency_at_Send_-_Max), 'NTB')"
    },
    {
     "target": "alias(maxSeries(sbnd.pmt*.BoardReader.*.Fragment_Latency_at_Send_-_Max), 'PMT')"
    },
    {
     "target": "alias(maxSeries(sbnd.ptb*.BoardReader.*.Fragment_Latency_at_Send_-_Max), 'PTB')"
    },
    {
     "target": "alias(maxSeries(sbnd.tdc.BoardReader.*.Fragment_Latency_at_Send_-_Max), 'SPEC TDC')"
    },
    {
     "target": "alias(maxSeries(sbnd.tpc*.BoardReader.*.Fragment_Latency_at_Send_-_Max), 'TPC')"
    },
    {
     "target": "alias(maxSeries(sbnd.xarapuca*.BoardReader.*.Fragment_Latency_at_Send_-_Max), 'XA')"
    }
   ]
  },
  {
   "title": "Fragement latency avg",
   "type": "timeseries",
   "description": "Fragment latency at send- max  \n(max series where there is more then one)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "alias(maxSeries(sbnd.crt*.BoardReader.*.Fragment_Latency_at_Send_-_Avg), 'CRT')"
    },
    {
     "target": "alias(maxSeries(sbnd.ntb*.BoardReader.*.Fragment_Latency_at_Send_-_Average), 'NTB')"
    },
    {
     "target": "alias(maxSeries(sbnd.pmt*.BoardReader.*.Fragment_Latency_at_Send_-_Average), 'PMT')"
    },
    {
     "target": "alias(maxSeries(sbnd.ptb*.BoardReader.*.Fragment_Latency_at_Send_-_Average), 'PTB')"
    },
    {
     "target": "alias(maxSeries(sbnd.tdc.BoardReader.*.Fragment_Latency_at_Send_-_Average), 'SPEC TDC')"
    },
    {
     "target": "alias(maxSeries(sbnd.tpc*.BoardReader.*.Fragment_Latency_at_Send_-_Average), 'TPC')"
    },
    {
     "target": "alias(maxSeries(sbnd.xarapuca*.BoardReader.*.Fragment_Latency_at_Send_-_Average), 'XA')"
    }
   ]
  },
  {
   "title": "Fragment Creation Gap Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "alias(sbnd.pmt*.BoardReader.40960.FragmentCreationGapMax, 'pmt01')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40961.FragmentCreationGapMax, 'pmt02')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40962.FragmentCreationGapMax, 'pmt03')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40963.FragmentCreationGapMax, 'pmt04')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40964.FragmentCreationGapMax, 'pmt05')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40965.FragmentCreationGapMax, 'pmt06')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40966.FragmentCreationGapMax, 'pmt07')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40967.FragmentCreationGapMax, 'pmt08')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40968.FragmentCreationGapMax, 'pmt09')"
    },
    {
     "target": "alias(sbnd.xarapuca*.BoardReader.41223.Fragment, 'xarapuca01')"
    }
   ]
  },
  {
   "title": "Fragment Creation Gap Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "alias(sbnd.pmt*.BoardReader.40960.FragmentCreationGapAvg, 'pmt01')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40961.FragmentCreationGapAvg, 'pmt02')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40962.FragmentCreationGapAvg, 'pmt03')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40963.FragmentCreationGapAvg, 'pmt04')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40964.FragmentCreationGapAvg, 'pmt05')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40965.FragmentCreationGapAvg, 'pmt06')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40966.FragmentCreationGapAvg, 'pmt07')"
    },
    {
     "target": "alias(sbnd.pmt*.BoardReader.40967.FragmentCreationGapAvg, 'pmt08')"
    }
   ]
  },
  {
   "title": "BoardReader*.Avg_Request_Response_Wait_Time",
   "type": "timeseries",
   "description": "BoardReader.*.Avg_Request_Response_Wait_Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sbnd.*.BoardReader.*.Avg_Request_Response_Wait_Time"
    }
   ]
  },
  {
   "title": "BoardReader*.Request_Response_Time",
   "type": "timeseries",
   "description": "BoardReader.*.Avg_Request_Response_Wait_Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sbnd.*.BoardReader.*.Request_Response_Time"
    }
   ]
  },
  {
   "title": "TPC BoardReader*.Avg_Request_Response_Wait_Time",
   "type": "timeseries",
   "description": "BoardReader.*.Avg_Request_Response_Wait_Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sbnd.tpc*.BoardReader.*.Avg_Request_Response_Wait_Time"
    }
   ]
  },
  {
   "title": "TPC BoardReader*.Request_Response_Time",
   "type": "timeseries",
   "description": "BoardReader.*.Avg_Request_Response_Wait_Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sbnd.tpc*.BoardReader.*.Request_Response_Time"
    }
   ]
  },
  {
   "title": "EventBuilder*.Avg_Fragment_Wait_Time_From_Rank_*",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*.Avg_Fragment_Wait_Time_From_Rank_*",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "sbnd.evb*.EventBuilder*.Avg_Fragment_Wait_Time_From_Rank_*"
    }
   ]
  },
  {
   "title": "EventBuilder*.Total_Shared_Memory_Wait_Time_From_Rank_*",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*.Total_Shared_Memory_Wait_Time_From_Rank_*",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "sbnd.evb*.EventBuilder*.Total_Shared_Memory_Wait_Time_From_Rank_*"
    }
   ]
  },
  { "title": "RAM etc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "EventBuilder*.AvailableRAM",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*.Total_Shared_Memory_Wait_Time_From_Rank_*",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.evb01.EventBuilder1.Available_RAM), 'evb01')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb02.EventBuilder2.Available_RAM), 'evb02')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb03.EventBuilder3.Available_RAM), 'evb03')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb04.EventBuilder4.Available_RAM), 'evb04')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb05.EventBuilder5.Available_RAM), 'evb05')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb06.EventBuilder6.Available_RAM), 'evb06')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb07.EventBuilder7.Available_RAM), 'evb07')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb08.EventBuilder8.Available_RAM), 'evb08')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb09.EventBuilder9.Available_RAM), 'evb09')"
    }
   ]
  },
  {
   "title": "EventBuilder*.FreeRAM",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*.Total_Shared_Memory_Wait_Time_From_Rank_*",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.evb01.EventBuilder1.Free_RAM), 'evb01')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb02.EventBuilder2.Free_RAM), 'evb02')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb03.EventBuilder3.Free_RAM), 'evb03')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb04.EventBuilder4.Free_RAM), 'evb04')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb05.EventBuilder5.Free_RAM), 'evb05')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb06.EventBuilder6.Free_RAM), 'evb06')"
    },
    {
     "target": "alias(sumSeries(sbnd.evb07.EventBuilder7.Free_RAM), 'evb07')"
    }
   ]
  },
  {
   "title": "sbnd.evb*.*.*.Process_RAM_Usage (art)",
   "type": "timeseries",
   "description": "sbnd.evb*.*.*.Process_CPU_Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(currentAbove(sbnd.evb01.EventBuilder*art*.Process_RAM_Usage, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb02.EventBuilder*art*.Process_RAM_Usage, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb03.EventBuilder*art*.Process_RAM_Usage, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb04.EventBuilder*art*.Process_RAM_Usage, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb05.EventBuilder*art*.Process_RAM_Usage, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb06.EventBuilder*art*.Process_RAM_Usage, -1), 2)"
    },
    {
     "target": "aliasByNode(currentAbove(sbnd.evb07.EventBuilder*art*.Process_RAM_Usage, -1), 2)"
    }
   ]
  },
  {
   "title": "sbnd.evb*.*.*.Process_RAM_Usage (no art)",
   "type": "timeseries",
   "description": "sbnd.evb*.*.*.Process_CPU_Usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "exclude(aliasByNode(currentAbove(sbnd.evb01.*.Process_RAM_Usage, -1), 2), 'art')"
    },
    {
     "target": "exclude(aliasByNode(currentAbove(sbnd.evb02.*.Process_RAM_Usage, -1), 2), 'art')"
    },
    {
     "target": "exclude(aliasByNode(currentAbove(sbnd.evb03.*.Process_RAM_Usage, -1), 2), 'art')"
    },
    {
     "target": "exclude(aliasByNode(currentAbove(sbnd.evb04.*.Process_RAM_Usage, -1), 2), 'art')"
    },
    {
     "target": "exclude(aliasByNode(currentAbove(sbnd.evb05.*.Process_RAM_Usage, -1), 2), 'art')"
    },
    {
     "target": "exclude(aliasByNode(currentAbove(sbnd.evb06.*.Process_RAM_Usage, -1), 2), 'art')"
    },
    {
     "target": "exclude(aliasByNode(currentAbove(sbnd.evb07.*.Process_RAM_Usage, -1), 2), 'art')"
    }
   ]
  },
  {
   "title": "sbnd.evb*.EventBuilder*_art*.Process_CPU_Usage",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*_art*.Process_CPU_Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "currentAbove(sbnd.evb*.EventBuilder*_art*.Process_CPU_Usage, -1)"
    }
   ]
  },
  {
   "title": "sbnd.evb*.EventBuilder*.Process_CPU_Usage - no art",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*.Process_CPU_Usage - no art",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "currentAbove(sbnd.evb*.EventBuilder*.Process_CPU_Usage, -1)"
    }
   ]
  },
  {
   "title": "sbnd.evb*.EventBuilder*_art*.Process_CPU_Idle",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*_art*.Process_CPU_Idle",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "currentAbove(sbnd.evb*.EventBuilder*_art*.System_CPU_Idle, -1)"
    }
   ]
  },
  {
   "title": "sbnd.evb*.EventBuilder*.Process_CPU_Idle - no art",
   "type": "timeseries",
   "description": "sbnd.evb*.EventBuilder*_art*.Process_CPU_Idle",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "currentAbove(sbnd.evb*.EventBuilder*.System_CPU_Idle, -1)"
    }
   ]
  },
  {
   "title": "sbnd.*.BoardReader.*.Process_CPU_Usage",
   "type": "timeseries",
   "description": "sbnd.*.BoardReader.*.Process_CPU_Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "sbnd.*.BoardReader.*.Process_CPU_Usage"
    }
   ]
  },
  {
   "title": "Total RAM (stacked)",
   "type": "timeseries",
   "description": "Total RAM usage by subsystem -- stacked",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.crt*.BoardReader.*.Total_RAM), 'CRT')"
    },
    {
     "target": "alias(sumSeries(sbnd.ntb*.BoardReader.*.Total_RAM), 'NTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.pmt*.BoardReader.*.Total_RAM), 'PMT')"
    },
    {
     "target": "alias(sumSeries(sbnd.ptb*.BoardReader.*.Total_RAM), 'PTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.Total_RAM), 'SPEC TDC')"
    },
    {
     "target": "alias(sumSeries(sbnd.tpc*.BoardReader.*.Total_RAM), 'TPC')"
    },
    {
     "target": "alias(sumSeries(sbnd.xarapuca*.BoardReader.*.Total_RAM), 'XA')"
    },
    {
     "target": "alias(sumSeries(sbnd.*.BoardReader.*.Total_RAM), 'Total')"
    }
   ]
  },
  {
   "title": "Board Reader Process RAM Usage (stacked)",
   "type": "timeseries",
   "description": "Total RAM usage by subsystem -- stacked",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sumSeries(sbnd.pmt00.BoardReader.*.Process_RAM_Usage), 'PMT')"
    },
    {
     "target": "alias(sumSeries(sbnd.crt*.BoardReader.*.Process_RAM_Usage), 'CRT')"
    },
    {
     "target": "alias(sumSeries(sbnd.ntb*.BoardReader.*.Process_RAM_Usage), 'NTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.tpc*.BoardReader.*.Process_RAM_Usage), 'TPC')"
    },
    {
     "target": "alias(sumSeries(sbnd.xarapuca*.BoardReader.*.Process_RAM_Usage), 'XA')"
    },
    {
     "target": "alias(sumSeries(sbnd.tdc.BoardReader.*.Process_RAM_Usage), 'SPEC-TDC')"
    },
    {
     "target": "alias(sumSeries(sbnd.ptb.BoardReader.*.Process_RAM_Usage), 'PTB')"
    },
    {
     "target": "alias(sumSeries(sbnd.*.BoardReader.*.Process_RAM_Usage), 'Total')"
    }
   ]
  },
  {
   "title": "Events Processed by EventBuilder ART Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 },
   "collapsed": true,
   "panels": [
    {
     "title": "EventBuilder*_art*.EventsProcessed",
     "type": "stat",
     "description": "sbnd.evb*.EventBuilder*_art*.EventsProcessed",
     "gridPos": { "h": 27, "w": 24, "x": 0, "y": 181 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "sbnd.evb0[1-3].EventBuilder*_art*.EventsProcessed"
      }
     ]
    }
   ]
  }
 ]
}