{
 "title": "TPC Board Temps EE",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "TPC EE01M Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "icarus.tpcee01m.BoardReader.4098.Temp.Board*.Temp*"
    }
   ]
  },
  {
   "title": "TPC EE01T Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "icarus.tpcee01t.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE02 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "icarus.tpcee02.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE01B Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "icarus.tpcee01b.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE04 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "icarus.tpcee04.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE03 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "icarus.tpcee03.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE06 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "icarus.tpcee06.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE05 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "target": "icarus.tpcee05.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE08 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "target": "icarus.tpcee08.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE07 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "target": "icarus.tpcee07.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE10 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "target": "icarus.tpcee10.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE09 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "target": "icarus.tpcee09.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE12 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "target": "icarus.tpcee12.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE11 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "target": "icarus.tpcee11.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE14 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "target": "icarus.tpcee14.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE13 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "target": "icarus.tpcee13.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE16 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "target": "icarus.tpcee16.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE15 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "target": "icarus.tpcee15.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE18 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "target": "icarus.tpcee18.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE17 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "target": "icarus.tpcee17.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE20T Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "target": "icarus.tpcee20t.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE19 Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "target": "icarus.tpcee19.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE20B Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "target": "icarus.tpcee20b.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE20M Board Temp Mean",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "target": "icarus.tpcee20m.BoardReader.0.Temp.*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE01M Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee01m.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE Board Temps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "icarus.tpcee*.BoardReader.0.Temp.Board*.Temp2"
    }
   ]
  },
  {
   "title": "TPC EE01T Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee01t.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE04 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee04.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE01B Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee01b.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE05 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee04.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE02 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee02.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE06 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee06.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE03 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee03.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE08 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee08.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE07 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee07.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE10 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee10.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE09 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee08.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE12 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee12.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE11 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee11.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE14 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 171 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee14.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE13 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee13.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE16 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee16.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE15 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee13.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE18 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee18.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE17 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee17.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE20T Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee20t.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE19 Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee19.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE20B Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee20m.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  },
  {
   "title": "TPC EE20M Board Temp Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "maxSeries(icarus.tpcee20m.BoardReader.0.Temp.Board*.Temp2)"
    }
   ]
  }
 ]
}