{
 "title": "DAQ Performance Monitor",
 "description": "https://github.com/art-daq/artdaq/wiki/Artdaq-built-in-metric-catalog",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "icarus.trigger.BoardReader.*.Fragment_Rate",
   "type": "timeseries",
   "description": "icarus.trigger.BoardReader.*.Fragment_Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "target": "icarus.trigger.BoardReader.*.Fragment_Rate"
    }
   ]
  },
  {
   "title": "EventBuilder*.Average_Event_Size",
   "type": "timeseries",
   "description": "EventBuilder*.Average_Event_Size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "icarus.evb01.EventBuilder1.Average_Event_Size"
    }
   ]
  },
  {
   "title": "BoardReader.*.Fragment_Buffer_Full_%",
   "type": "timeseries",
   "description": "icarus.*.BoardReader.*.Fragment_Buffer_Full_%",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.Fragment_Buffer_Full_%"
    }
   ]
  },
  {
   "title": "EventBuilder*.Shared_Memory_Full_%",
   "type": "timeseries",
   "description": "icarus.*.EventBuilder*.Shared_Memory_Full_%",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "icarus.*.EventBuilder*.Shared_Memory_Full_%"
    }
   ]
  },
  {
   "title": "BoardReader*.Avg_Request_Response_Wait_Time",
   "type": "timeseries",
   "description": "BoardReader.*.Avg_Request_Response_Wait_Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.Avg_Request_Response_Wait_Time"
    }
   ]
  },
  {
   "title": "EventBuilder*.Average_Event_Building_Time",
   "type": "timeseries",
   "description": "icarus.*.EventBuilder*.Average_Event_Building_Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "icarus.*.EventBuilder*.Average_Event_Building_Time"
    }
   ]
  },
  {
   "title": "EventBuilder*.Back-pressure_wait_time",
   "type": "timeseries",
   "description": "icarus.evb0*.EventBuilder*.Back-pressure_wait_time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "icarus.evb0*.EventBuilder*.Back-pressure_wait_time"
    }
   ]
  },
  {
   "title": "EventBuilder*_art*.EventsProcessed",
   "type": "stat",
   "description": "icarus.evb*.EventBuilder*_art*.EventsProcessed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "icarus.evb*.EventBuilder*_art*.EventsProcessed"
    }
   ]
  },
  {
   "title": "EventBuilder**_art*.Avg_Processing_Time",
   "type": "timeseries",
   "description": "icarus.evb*.EventBuilder**_art*.Avg_Processing_Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "icarus.evb*.EventBuilder**_art*.Avg_Processing_Time"
    }
   ]
  },
  {
   "title": "EventBuilder*.Avg_Fragment_Wait_Time_From_Rank_*",
   "type": "timeseries",
   "description": "icarus.evb*.EventBuilder*.Avg_Fragment_Wait_Time_From_Rank_*",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "icarus.evb*.EventBuilder*.Avg_Fragment_Wait_Time_From_Rank_*"
    }
   ]
  },
  {
   "title": "EventBuilder*.Total_Shared_Memory_Wait_Time_From_Rank_*",
   "type": "timeseries",
   "description": "icarus.evb*.EventBuilder*.Total_Shared_Memory_Wait_Time_From_Rank_*",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "icarus.evb*.EventBuilder*.Total_Shared_Memory_Wait_Time_From_Rank_*"
    }
   ]
  },
  {
   "title": "EventBuilder*.Avg_Fragment_Wait_Time_From_Rank_*",
   "type": "timeseries",
   "description": "icarus.*.EventBuilder*.Avg_Fragment_Wait_Time_From_Rank_*",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "icarus.*.EventBuilder*.Avg_Fragment_Wait_Time_From_Rank_*"
    }
   ]
  },
  {
   "title": "EventBuilder*_art*.EventsWithMissingFragments",
   "type": "timeseries",
   "description": "icarus.evb*.EventBuilder*_art*.EventsWithMissingFragments",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "target": "icarus.evb*.EventBuilder*_art*.EventsWithMissingFragments"
    }
   ]
  },
  {
   "title": "EventBuilder*_art*.EventsWithEmptyFragments",
   "type": "timeseries",
   "description": "icarus.evb*.EventBuilder*_art*.EventsWithEmptyFragments",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "target": "icarus.evb*.EventBuilder*_art*.EventsWithEmptyFragments"
    }
   ]
  }
 ]
}