{
 "title": "CAEN 1730 Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CAEN Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CAEN Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "groupByNode(icarus.icaruspmt*.BoardReader.*.CAENV1730.*.*.Temp, 1, 'maxSeries')"
    }
   ]
  },
  {
   "title": "CAEN Memory Full",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "groupByNode(icarus.icaruspmt*.BoardReader.*.CAENV1730.*.*.MemoryFull, 1, 'sum')"
    }
   ]
  },
  {
   "title": "CAEN Status",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "icarus.icaruspmt*.BoardReader.*.CAENV1730.*.*.Status"
    }
   ]
  },
  {
   "title": "Missing Fragments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Missing_Fragments, 1)"
    }
   ]
  },
  { "title": "Board Reader Core Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Data_Rate, 1)"
    }
   ]
  },
  {
   "title": "Fragment Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Fragment_Rate, 1)"
    }
   ]
  },
  {
   "title": "Buffer Depth Fragments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Buffer_Depth_Fragments, 1)"
    }
   ]
  },
  {
   "title": "Fragment Buffer Full %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Fragment_Buffer_Full_%, 1)"
    }
   ]
  },
  {
   "title": "Request Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Request_Response_Time, 1)"
    }
   ]
  },
  {
   "title": "Fragment Create Time (Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Fragment_Create_Time__Max, 1)"
    }
   ]
  },
  {
   "title": "Fragment Latency at Send (Average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Fragment_Latency_at_Send_-_Average, 1)"
    }
   ]
  },
  {
   "title": "Fragment Latency at Send (Max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.Fragment_Latency_at_Send_-_Max, 1)"
    }
   ]
  }
 ]
}