{
 "title": "BH - OM - sandbox",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 20, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "icarus.tpcw*.BoardReader.0.Average_Fragment_Size"
    },
    {
     "target": "icarus.icaruspmte*.BoardReader.*.Average_Fragment_Size"
    }
   ]
  },
  {
   "title": "evb01 /data disk monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "icarus.icarus-evb01.data.Percent_Used"
    }
   ]
  },
  {
   "title": "ALARM: TPC BoardReaders Busy",
   "type": "stat",
   "description": "This panel should read 0 if the intended TPC boards are being read as expected. If one goes into the \"busy\" status, this box will turn red.\n\nIn this case, there is an issue.",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(icarus.tpc*.BoardReader.*.Status.N_Busy_-_Max)"
    }
   ]
  },
  {
   "title": "ALARM: Circular Buffers",
   "type": "stat",
   "description": "This shows the maximum circular buffer occupancy across the elements in the run.\n\nIf this box goes red then the circular buffers are acting outside of expected conditions.",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(icarus.*.BoardReader.*.GetData.CircularBufferOccupancy_-_Average)"
    }
   ]
  },
  {
   "title": "Run Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "icarus.dl01.DataLogger1.Run_Number"
    }
   ]
  },
  {
   "title": "Channel Baseline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "icarus.om.tpc_channel:4100:baseline"
    },
    {
     "target": "icarus.om.tpc_channel:3600:baseline"
    }
   ]
  },
  {
   "title": "Channel RMS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "icarus.om.tpc_channel:3600:rms" },
    { "target": "icarus.om.tpc_channel:4100:rms" }
   ]
  }
 ]
}