{
 "title": "Shifter DAQ Status Copy",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last Run Number (partition 1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "icarus.partition1.run_number" }
   ]
  },
  {
   "title": "Total Event Rates",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(keepLastValue(icarus.tpce*.BoardReader.*.Fragment_Rate, 10)), 'TPC (East) Avg Rate')"
    },
    {
     "target": "alias(averageSeries(keepLastValue(icarus.tpcw*.BoardReader.*.Fragment_Rate, 10)), 'TPC (West) Avg Rate')"
    },
    {
     "target": "alias(averageSeries(keepLastValue(icarus.*pmt*.BoardReader.*.Fragment_Rate, 10)), 'PMT Avg Fragment Rate')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Event_Rate, 10)), 'EventBuilder Event Rate')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.disp01.*.Event_Rate)), 'Dispatcher Event Rate')"
    }
   ]
  },
  {
   "title": "Trigger Rates",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.EventRate, 10), 0), 'Total')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.BNBEventRate, 10), 0), 'BNB')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.NuMIEventRate, 10), 0), 'NuMI')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.BNBOffbeamEventRate, 10), 0), 'BNBOffBeam')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.NuMIOffbeamEventRate, 10), 0), 'NuMIOffBeam')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.OtherEventRate, 10), 0), 'Other')"
    }
   ]
  },
  {
   "title": "Beam Early Warning Signals ",
   "type": "gauge",
   "description": "Rate of the beam signals transmitted through the White Rabbit network",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(transformNull(keepLastValue(icarus.daq02.*.*.WR_CLK02_SPEC_DIO_gatedBES.DIO_Channel_4_Rates, 10), 0), 'BNB Gated BES')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.daq02.*.*.WR_CLK02_SPEC_DIO_$1D.DIO_Channel_1_Rates, 10), 0), 'BNB $1D')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.daq02.BoardReader.*.WR_CLK02_SPEC_DIO_$74.DIO_Channel_3_Rates, 10), 0), 'NuMI MIBS $74')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.daq02.BoardReader.*.WR_CLK02_SPEC_DIO_$AE.DIO_Channel_2_Rates, 10), 0), 'NuMI $AD')"
    }
   ]
  },
  {
   "title": "Events Released To Art From This Run",
   "type": "table-old",
   "description": "This shows the number of events collected for this run.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.dl*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.disp*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in Dispatchers')"
    }
   ]
  },
  {
   "title": "Incomplete Events Released To Art From This Run",
   "type": "table-old",
   "description": "In the ideal case, there are no incomplete events. If you start seeing incomplete events, make note of this in the ECL!",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Incomplete Events in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.dl*.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Inomplete Events in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.disp01.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Inomplete Events in Dispatchers')"
    }
   ]
  },
  {
   "title": "ALARM: TPC BoardReaders Busy",
   "type": "stat",
   "description": "This panel should read 0 if the intended TPC boards are being read as expected. If one goes into the \"busy\" status, this box will turn red.\n\nIn this case, there is an issue.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(icarus.tpc*.BoardReader.*.Status.N_Busy_-_Max)"
    }
   ]
  },
  {
   "title": "ALARM: PMT Digitizers",
   "type": "stat",
   "description": "Monitor for the internal temperature of the CAENV1730. It turns red when the temperature exceeds 65 degrees. A run should be stopped if this occurrence happens",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(maxSeries(keepLastValue(icarus.icaruspmt*.BoardReader.*.CAENV1730.*.*.Temp)), 'PMT Max temperature')"
    }
   ]
  },
  {
   "title": "ALARM: PMT Digitizers Busy",
   "type": "stat",
   "description": "This panel should read 0 if the intended PMT boards are being read as expected. If one goes into the \"busy\" status, this box will turn red.\n\nIn this case, there is an issue.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(icarus.icaruspmt*.BoardReader.*.CAENV1730.*.*.MemoryFull)"
    }
   ]
  },
  {
   "title": "ALARM: TPC Circular Buffers Occupancy",
   "type": "stat",
   "description": "This shows the maximum circular buffer occupancy across the elements in the run.\n\nIf this box goes red then the circular buffers are acting outside of expected conditions.",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(keepLastValue(icarus.tpc*.BoardReader.*.GetData.CircularBufferOccupancy_-_Average))"
    }
   ]
  },
  {
   "title": "/data Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(icarus.icarus-evb01.data.Percent_Used, 'icarus-evb01')"
    },
    {
     "target": "alias(icarus.icarus-evb02.data.Percent_Used, 'icaurs-evb02')"
    },
    {
     "target": "alias(icarus.icarus-evb03.data.Percent_Used, 'icarus-evb03')"
    },
    {
     "target": "alias(icarus.icarus-evb04.data.Percent_Used, 'icarus-evb04')"
    },
    {
     "target": "alias(icarus.icarus-evb05.data.Percent_Used, 'icarus-evb05')"
    },
    {
     "target": "icarus.icarus-evb06.data.Percent_Used"
    }
   ]
  },
  {
   "title": "CRT Hit Rates (corrected for lost hits)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.feb_hit_rate_Hz_*"
    }
   ]
  },
  {
   "title": "PMT Fragments rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "keepLastValue(icarus.icaruspmt*.*.*.Fragment_Rate, 10)"
    }
   ]
  },
  {
   "title": "/daq/log monitoring",
   "type": "gauge",
   "description": "displays the Usage of /daq/log/ partition on evb machines",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "icarus.icarus-evb06.daq_log.Percent_Used"
    }
   ]
  },
  {
   "title": "Events with empty fragments",
   "type": "stat",
   "description": "total number empty fragments collected this run",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.EventBuilder*_art*.EventsWithEmptyFragmentsOnPMT, 100)), 'PMT')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.EventBuilder*_art*.EventsWithEmptyFragmentsOnCRT, 100)), 'CRT')"
    }
   ]
  },
  {
   "title": "Events with empty fragments [%]",
   "type": "stat",
   "description": "the rate of the total empty fragments collected normalized to the total number of events collected",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A/$B)*100", "type": "math" },
    { "expression": "($C/$B)*100", "type": "math" }
   ]
  },
  {
   "title": "/scratch_local Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /scratch_local area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icarus-evb01.scratch_local.Percent_Used, 1)"
    },
    {
     "target": "aliasByNode(icarus.icarus-evb02.scratch_local.Percent_Used, 1)"
    },
    {
     "target": "aliasByNode(icarus.icarus-evb03.scratch_local.Percent_Used, 1)"
    },
    {
     "target": "aliasByNode(icarus.icarus-evb04.scratch_local.Percent_Used, 1)"
    },
    {
     "target": "aliasByNode(icarus.icarus-evb05.scratch_local.Percent_Used, 1)"
    },
    {
     "target": "aliasByNode(icarus.icarus-evb06.scratch_local.Percent_Used, 1)"
    }
   ]
  }
 ]
}