{
 "title": "D-state Reporting",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Wait Average",
   "type": "graph",
   "description": "Shows wait averages reported by the top utility.",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "icarus.*.wait_average" }
   ]
  },
  {
   "title": "\"D\"-state count",
   "type": "graph",
   "description": "Number of processes in the \"D\"-state reported by the top utility.",
   "gridPos": { "h": 13, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "icarus.*.dstate_count" }
   ]
  },
  {
   "title": "CPU total for \"D\"-state processes",
   "type": "graph",
   "description": "Shows total CPU usages for processes in the \"D\" state as reported by the top utility.",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "icarus.*.procs_in_dstate.*.cpu_total"
    }
   ]
  },
  {
   "title": "\"D\"-state instance count",
   "type": "graph",
   "description": "Show the number of process instances in the \"D\"-state as reported by the top utility.",
   "gridPos": { "h": 15, "w": 9, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "icarus.*.procs_in_dstate.*.instance_count"
    }
   ]
  }
 ]
}