{
 "title": "Artdaq_TPC_fragments",
 "description": "some TPC minicrate fragment metrics for viewing...",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fragment Rate",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasByNode(icarus.tpc04.BoardReader.*.Fragment_Rate, 1)"
    },
    {
     "target": "aliasByNode(icarus.tpcwe07.BoardReader.*.Fragment_Rate, 1)"
    },
    {
     "target": "aliasByNode(icarus.tpcwe09.BoardReader.*.Fragment_Rate, 1)"
    },
    {
     "target": "aliasByNode(icarus.tpcew05.BoardReader.*.Fragment_Rate, 1)"
    },
    {
     "target": "aliasByNode(icarus.tpcew07.BoardReader.*.Fragment_Rate, 1)"
    },
    {
     "target": "aliasByNode(icarus.tpcew09.BoardReader.*.Fragment_Rate, 1)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Avg Fragment Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.tpc*.BoardReader.*.Average_Fragment_Size, 1)"
    }
   ]
  },
  {
   "title": "Avg Fragment Latency at Send",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.tpc*.BoardReader.*.Fragment_Latency_at_Send_-_Average, 1)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Circular Buffer Occupancy in getNext() Last",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.*.*.*.getNext.CircularBufferOccupancy_-_Last, 1)"
    }
   ]
  },
  {
   "title": "Circular Buffer Occupancy in getNext() Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.*.*.*.getNext.CircularBufferOccupancy_-_Max, 1)"
    }
   ]
  },
  {
   "title": "Circular Buffer Occupancy in GetData() Last",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.*.*.*.GetData.CircularBufferOccupancy_-_Last, 1)"
    }
   ]
  },
  {
   "title": "Circular Buffer Occupancy in GetData() Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.*.*.*.GetData.CircularBufferOccupancy_-_Max, 1)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Circular Buffer Linearize Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(icarus.*.*.*.CircularBuffer.LinearizeCount, 1), 1)"
    }
   ]
  },
  {
   "title": "Circular Buffer Linearize Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(icarus.*.*.*.CircularBuffer.LinearizeCount, 1), 1)"
    }
   ]
  }
 ]
}