{
 "title": "PMT Monitoring",
 "description": "Dashboard for the monitor of the PMTs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Hardware Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CAEN Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "groupByNode(icarus.icaruspmt*.BoardReader.*.CAENV1730.*.*.Temp, 1, 'maxSeries')"
    }
   ]
  },
  {
   "title": "Events with empty fragments",
   "type": "timeseries",
   "description": "the rate of the total empty fragments collected normalized to the total number of events collected",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(removeBelowValue(icarus.evb*.EventBuilder*_art*.EventsWithEmptyFragments,1), 10)), 'Events with Empty Fragments')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(removeBelowValue(icarus.evb*.EventBuilder*_art*.EventsWithEmptyFragmentsOnPMT,1), 10)), 'Events with PMT Empty fragments')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(removeBelowValue(icarus.evb*.EventBuilder*_art*.EventsWithEmptyFragmentsOnCRT,1), 10)), 'Events with CRT Empty fragments')"
    }
   ]
  },
  {
   "title": "DEBUGGING empty fragments metric queries",
   "type": "timeseries",
   "description": "the rate of the total empty fragments collected normalized to the total number of events collected",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "icarus.evb07.EventBuilder7_art6.EventsWithEmptyFragmentsOnPMT"
    },
    {
     "target": "removeBelowValue(icarus.evb07.EventBuilder7_art6.EventsWithEmptyFragmentsOnPMT,1)"
    },
    {
     "target": "keepLastValue(removeBelowValue(icarus.evb07.EventBuilder7_art6.EventsWithEmptyFragmentsOnPMT,1),100)"
    }
   ]
  },
  {
   "title": "Events with empty fragments  [%]",
   "type": "stat",
   "description": "the rate of the total empty fragments collected normalized to the total number of events collected",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(sumSeries(transformNull(keepLastValue(removeBelowValue(icarus.evb*.EventBuilder*_art*.EventsWithEmptyFragmentsOnPMT,1), 5000),0)), 'PMT')"
    },
    {
     "target": "alias(sumSeries(transformNull(keepLastValue(removeBelowValue(icarus.evb*.EventBuilder*_art*.EventsWithEmptyFragmentsOnCRT,1), 5000),0)), 'CRT')"
    }
   ]
  },
  {
   "title": "Events with empty fragments [%]",
   "type": "stat",
   "description": "the rate of the total empty fragments collected normalized to the total number of events collected",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A/$B)*100", "type": "math" },
    { "expression": "($C/$B)*100", "type": "math" }
   ]
  },
  {
   "title": "Events with empty fragments [%]",
   "type": "timeseries",
   "description": "the rate of the total empty fragments collected normalized to the total number of events collected",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    { "expression": "($A/$B)*100", "type": "math" },
    { "expression": "($C/$B)*100", "type": "math" }
   ]
  },
  {
   "title": "PMT Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "icarus.icaruspmt*.BoardReader.*.CAENV1730.Card0.*.Status"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "icarus.*pmt*.*.*.Average_Fragment_Size"
    }
   ]
  },
  {
   "title": "PMT Busy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "icarus.icaruspmt*.BoardReader.*.CAENV1730.*.*.MemoryFull"
    }
   ]
  },
  {
   "title": "Fragment create Time ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "maxSeries(icarus.icaruspmt*.BoardReader.*.FragmentCreationGapMax)"
    }
   ]
  },
  {
   "title": "PMT Temps",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "icarus.icaruspmt*.BoardReader.*.CAENV1730.Card0.*.Temp"
    }
   ]
  },
  {
   "title": "Fragment Buffer full %",
   "type": "timeseries",
   "description": "Fraction of filled fragment buffer",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "maxSeries(icarus.icaruspmt*.*.*.Fragment_Buffer_Full_%)"
    }
   ]
  },
  {
   "title": "Fragment create Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "maxSeries(icarus.icaruspmt*.BoardReader.*.Fragment_Create_Time__Max)"
    }
   ]
  },
  {
   "title": "PMT Busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.CAENV1730.*.*.MemoryFull, 1)"
    }
   ]
  },
  {
   "title": "Fragment latency at sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "target": "maxSeries(icarus.icaruspmt*.BoardReader.*.Fragment_Latency_at_Send_-_Max)"
    }
   ]
  },
  {
   "title": "PMT Temps",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "target": "alias(maxSeries(icarus.icaruspmt*.BoardReader.*.CAENV1730.Card0.*.Temp), 'PMT Max temperature')"
    }
   ]
  },
  {
   "title": "Missing PMT Fragments",
   "type": "timeseries",
   "description": "Number of missing fragments from PMTs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "target": "sumSeries(icarus.icaruspmt*.*.*.Missing_Fragments, icarus.icaruspmt*.*.Missing_Fragments)"
    }
   ]
  },
  {
   "title": "PMT Temps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(icarus.icaruspmt*.BoardReader.*.CAENV1730.Card0.*.Temp, 1)"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "targets": [
    {}
   ]
  }
 ]
}