{
 "title": "DEVELOPMENT - Shifter DAQ Status",
 "description": "This dashboard is the one intended for use by the shifter. The others are generally expert level :)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Run Number (partition 1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "icarus.partition1.run_number" }
   ]
  },
  {
   "title": "Total Event Rates",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(keepLastValue(icarus.tpce*.BoardReader.*.Fragment_Rate, 10)), 'TPC (East) Avg Rate')"
    },
    {
     "target": "alias(averageSeries(keepLastValue(icarus.tpcw*.BoardReader.*.Fragment_Rate, 10)), 'TPC (West) Avg Rate')"
    },
    {
     "target": "alias(averageSeries(keepLastValue(icarus.*pmt*.BoardReader.*.Fragment_Rate, 10)), 'PMT Avg Fragment Rate')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Event_Rate, 10)), 'EventBuilder Event Rate')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.disp01.*.Event_Rate)), 'Dispatcher Event Rate')"
    }
   ]
  },
  {
   "title": "Trigger Rates",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.EventRate, 10), 0), 'Total')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.BNBEventRate, 10), 0), 'BNB')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.NuMIEventRate, 10), 0), 'NuMI')"
    },
    {
     "target": "alias(transformNull(keepLastValue(icarus.trigger.BoardReader.*.OtherEventRate, 10), 0), 'Other')"
    }
   ]
  },
  {
   "title": "Events Released To Art From This Run",
   "type": "table-old",
   "description": "This shows the number of events collected for this run.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.dl*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.disp*.*.Events_Released_to_art_this_run, 10)), 'Events Released to art in Dispatchers')"
    }
   ]
  },
  {
   "title": "Incomplete Events Released To Art From This Run",
   "type": "table-old",
   "description": "In the ideal case, there are no incomplete events. If you start seeing incomplete events, make note of this in the ECL!",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(icarus.evb*.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Incomplete Events in EventBuilders')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.dl*.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Inomplete Events in DataLoggers')"
    },
    {
     "target": "alias(sumSeries(keepLastValue(icarus.disp01.*.Incomplete_Events_Released_to_art_this_run, 10)), 'Inomplete Events in Dispatchers')"
    }
   ]
  },
  {
   "title": "ALARM: TPC BoardReaders Busy",
   "type": "stat",
   "description": "This panel should read 0 if the intended TPC boards are being read as expected. If one goes into the \"busy\" status, this box will turn red.\n\nIn this case, there is an issue.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(icarus.tpc*.BoardReader.*.Status.N_Busy_-_Max)"
    }
   ]
  },
  {
   "title": "ALARM: PMT Digitizers Busy",
   "type": "stat",
   "description": "This panel should read 0 if the intended PMT boards are being read as expected. If one goes into the \"busy\" status, this box will turn red.\n\nIn this case, there is an issue.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sumSeries(icarus.icaruspmt*.BoardReader.*.CAENV1730.*.*.MemoryFull)"
    }
   ]
  },
  {
   "title": "ALARM: TPC Circular Buffers Occupancy",
   "type": "stat",
   "description": "This shows the maximum circular buffer occupancy across the elements in the run.\n\nIf this box goes red then the circular buffers are acting outside of expected conditions.",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maxSeries(keepLastValue(icarus.tpc*.BoardReader.*.GetData.CircularBufferOccupancy_-_Average))"
    }
   ]
  },
  {
   "title": "/data Usage Monitor",
   "type": "gauge",
   "description": "Shows how much of the /data area on evb01 is being used.\n\nIt's set to go orange above 60%, meaning take note, and it's set to go red above 95%, meaning alarm.",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(icarus.icarus-evb01.data.Percent_Used, 'icarus-evb01')"
    },
    {
     "target": "alias(icarus.icarus-evb02.data.Percent_Used, 'icaurs-evb02')"
    },
    {
     "target": "alias(icarus.icarus-evb03.data.Percent_Used, 'icarus-evb03')"
    },
    {
     "target": "alias(icarus.icarus-evb04.data.Percent_Used, 'icarus-evb04')"
    },
    {
     "target": "alias(icarus.icarus-evb05.data.Percent_Used, 'icarus-evb05')"
    },
    {
     "target": "icarus.icarus-evb06.data.Percent_Used"
    }
   ]
  },
  {
   "title": "CRT Hit Rates (corrected for lost hits)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.feb_hit_rate_Hz_*"
    }
   ]
  },
  {
   "title": "PMT Fragments rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "icarus.icaruspmt*.*.*.Fragment_Rate"
    }
   ]
  }
 ]
}