{
 "title": "Icarus Gennadiy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Last Run Number",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "icarus.run_number" }
   ]
  },
  {
   "title": "/data disk monitor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "icarus.icarus-evb*.data.Percent_Used"
    }
   ]
  },
  {
   "title": "Total Event Rates",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "alias(averageSeries(icarus.tpc*.BoardReader.*.Fragment_Rate), 'TPC Avg Fragment Rate')"
    },
    {
     "target": "alias(averageSeries(icarus.*pmt*.BoardReader.*.Fragment_Rate), 'PMT Avg Fragment Rate')"
    },
    {
     "target": "alias(sumSeries(icarus.evb*.*.Event_Rate), 'EventBuilder Event Rate')"
    },
    {
     "target": "alias(sumSeries(icarus.dl*.*.Event_Rate), 'DataLogger Event Rate')"
    },
    {
     "target": "alias(sumSeries(icarus.*crt*.BoardReader.*.Fragment_Rate), 'CRT Avg Fragment Rate')"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "icarus.*.*.*.System_CPU_Usage" }
   ]
  },
  {
   "title": "Network Send Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "icarus.*.*.*.Network_Send_Rate" }
   ]
  },
  {
   "title": "Event Rates",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "target": "icarus.*.*.Event_Rate" },
    {
     "target": "sumSeries(icarus.evb*.*.Event_Rate)"
    }
   ]
  },
  {
   "title": "Board Readers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "target": "icarus.*.BoardReader.*.Data_Rate"
    },
    {
     "target": "icarus.*.BoardReader.*.Fragment_Rate"
    }
   ]
  },
  {
   "title": "Event Builders",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes/Event" }
   ],
   "targets": [
    {
     "target": "icarus.evb*.*.Average_Event_Size"
    },
    { "target": "icarus.evb*.*.Event_Rate" }
   ]
  },
  {
   "title": "Released Events",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "icarus.*.*.Events_Released_to_art_this_run"
    },
    {
     "target": "icarus.*.*.Incomplete_Events_Released_to_art_this_run"
    }
   ]
  },
  {
   "title": "Data Loggers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps", "label": "DataWrite Rate" }
   ],
   "targets": [
    {
     "target": "alias(icarus.*.DataLogger*.Data_Receive_Rate_From_*, 'DataReceive_Rates')"
    },
    {
     "target": "sumSeries(icarus.*.DataLogger*.Event_Rate)"
    }
   ]
  }
 ]
}