{
 "title": "CRT Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fragment Container Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.Fragment_Rate"
    }
   ]
  },
  {
   "title": "Average Fragment Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.Average_Fragment_Size"
    }
   ]
  },
  {
   "title": "Feb Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.feb_hit_rate_Hz_*"
    }
   ]
  },
  {
   "title": "Board Reader CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.Process_CPU_Usage"
    }
   ]
  },
  {
   "title": "Time spent outside of getNext_()",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.time_outside_getNext_ms"
    }
   ]
  },
  {
   "title": "FEB buffer size (Fragments read by getNext_())",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.max_feb_buffer_size"
    }
   ]
  },
  {
   "title": "time spent inside getNext_()",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.getNext_execution_time_ms"
    }
   ]
  },
  {
   "title": "Time spent outside GetFEBData()",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "icarus.crt0*.BoardReader.*.time_outside_GetFEBData_ms"
    }
   ]
  },
  {
   "title": "Time spent inside GetFEBData()",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.GetFEBData_execution_time_ms"
    }
   ]
  },
  {
   "title": "Time spent reading data from FEBs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.time_reading_FEBs_ms"
    }
   ]
  },
  {
   "title": "Time spent waiting for poll",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "icarus.crt*.BoardReader.*.time_waiting_for_poll_ms"
    }
   ]
  }
 ]
}