{
 "title": "Bottom CRT",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average difference between fragment timestamps and Unix time at getNext_",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "icarus.crtbottom*.BoardReader.*.Timestamp_difference_-_Average"
    }
   ]
  },
  {
   "title": "Fragments made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "icarus.crtbottom*.BoardReader.*.Fragments_Made"
    },
    {}
   ]
  },
  {
   "title": "Fragments sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "target": "icarus.crtbottom*.*.*.Fragments_Sent"
    }
   ]
  },
  {
   "title": "Maximum difference between fragment timestamps and Unix time in getNext_",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "icarus.crtbottom*.BoardReader.*.Timestamp_difference_-_Max"
    }
   ]
  },
  {
   "title": "Average fragment size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "icarus.crtbottom*.*.*.Average_Fragment_Size"
    }
   ]
  },
  {
   "title": "Minimum difference between fragment timestamps and Unix time in getNext_",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "icarus.crtbottom*.BoardReader.*.Timestamp_difference_-_Min"
    }
   ]
  },
  {
   "title": "Fragment container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "target": "icarus.crtbottom*.*.*.Fragment_Rate"
    }
   ]
  }
 ]
}