{
 "title": "TPC Board Temps EE Giovanni JSON TRIAL",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "target": "icarus.partition1.run_number" }
   ]
  },
  {
   "title": "TPC EE01T",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "icarus.tpcee01t.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE20T",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "icarus.tpcee20t.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW01T",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "target": "icarus.tpcew01t.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW20T",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "target": "icarus.tpcew20t.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE01T",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "target": "icarus.tpcwe01t.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE20T",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "target": "icarus.tpcwe20t.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW01T",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "target": "icarus.tpcww01t.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW20T",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "target": "icarus.tpcww20t.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE01M",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "target": "icarus.tpcee01m.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE01B",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "target": "icarus.tpcee01b.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE02",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "target": "icarus.tpcee02.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE03",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "target": "icarus.tpcee03.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE04",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "target": "icarus.tpcee04.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE05",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "target": "icarus.tpcee05.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE06",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 139 },
   "targets": [
    {
     "target": "icarus.tpcee06.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE07",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "target": "icarus.tpcee07.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE08",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 165 },
   "targets": [
    {
     "target": "icarus.tpcee08.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE09",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 178 },
   "targets": [
    {
     "target": "icarus.tpcee09.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE10",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 191 },
   "targets": [
    {
     "target": "icarus.tpcee10.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE11",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 204 },
   "targets": [
    {
     "target": "icarus.tpcee11.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE12",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 217 },
   "targets": [
    {
     "target": "icarus.tpcee12.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE13",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 230 },
   "targets": [
    {
     "target": "icarus.tpcee13.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE14",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 243 },
   "targets": [
    {
     "target": "icarus.tpcee14.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE15",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 256 },
   "targets": [
    {
     "target": "icarus.tpcee15.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE16",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 269 },
   "targets": [
    {
     "target": "icarus.tpcee16.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE17",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 282 },
   "targets": [
    {
     "target": "icarus.tpcee17.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE18",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 295 },
   "targets": [
    {
     "target": "icarus.tpcee18.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE19",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 308 },
   "targets": [
    {
     "target": "icarus.tpcee19.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE20M",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 321 },
   "targets": [
    {
     "target": "icarus.tpcee20m.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EE20B",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 334 },
   "targets": [
    {
     "target": "icarus.tpcee20b.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW01M",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 347 },
   "targets": [
    {
     "target": "icarus.tpcew01m.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW01B",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 360 },
   "targets": [
    {
     "target": "icarus.tpcew01b.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW02",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 373 },
   "targets": [
    {
     "target": "icarus.tpcew02.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW03",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 386 },
   "targets": [
    {
     "target": "icarus.tpcew03.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW04",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 399 },
   "targets": [
    {
     "target": "icarus.tpcew04.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW05",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 412 },
   "targets": [
    {
     "target": "icarus.tpcew05.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW06",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 425 },
   "targets": [
    {
     "target": "icarus.tpcew06.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW07",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 438 },
   "targets": [
    {
     "target": "icarus.tpcew07.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW08",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 451 },
   "targets": [
    {
     "target": "icarus.tpcew08.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW09",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 464 },
   "targets": [
    {
     "target": "icarus.tpcew09.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW10",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 477 },
   "targets": [
    {
     "target": "icarus.tpcew10.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW11",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 490 },
   "targets": [
    {
     "target": "icarus.tpcew11.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW12",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 503 },
   "targets": [
    {
     "target": "icarus.tpcew12.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW13",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 516 },
   "targets": [
    {
     "target": "icarus.tpcew13.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW14",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 529 },
   "targets": [
    {
     "target": "icarus.tpcew14.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW15",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 542 },
   "targets": [
    {
     "target": "icarus.tpcew15.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW16",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 555 },
   "targets": [
    {
     "target": "icarus.tpcew16.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW17",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 568 },
   "targets": [
    {
     "target": "icarus.tpcew17.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW18",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 581 },
   "targets": [
    {
     "target": "icarus.tpcew18.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW19",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 594 },
   "targets": [
    {
     "target": "icarus.tpcew19.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW20M",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 607 },
   "targets": [
    {
     "target": "icarus.tpcew20m.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC EW20B",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 620 },
   "targets": [
    {
     "target": "icarus.tpcew20b.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE01M",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 633 },
   "targets": [
    {
     "target": "icarus.tpcwe01m.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE01B",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 646 },
   "targets": [
    {
     "target": "icarus.tpcwe01b.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE02",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 659 },
   "targets": [
    {
     "target": "icarus.tpcwe02.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE03",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 672 },
   "targets": [
    {
     "target": "icarus.tpcwe03.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE04",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 685 },
   "targets": [
    {
     "target": "icarus.tpcwe04.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE05",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 698 },
   "targets": [
    {
     "target": "icarus.tpcwe05.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE06",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 711 },
   "targets": [
    {
     "target": "icarus.tpcwe06.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE07",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 724 },
   "targets": [
    {
     "target": "icarus.tpcwe07.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE08",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 737 },
   "targets": [
    {
     "target": "icarus.tpcwe08.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE09",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 750 },
   "targets": [
    {
     "target": "icarus.tpcwe09.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE10",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 763 },
   "targets": [
    {
     "target": "icarus.tpcwe10.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE11",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 776 },
   "targets": [
    {
     "target": "icarus.tpcwe11.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE12",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 789 },
   "targets": [
    {
     "target": "icarus.tpcwe12.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE13",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 802 },
   "targets": [
    {
     "target": "icarus.tpcwe13.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE14",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 815 },
   "targets": [
    {
     "target": "icarus.tpcwe14.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE15",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 828 },
   "targets": [
    {
     "target": "icarus.tpcwe15.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE16",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 841 },
   "targets": [
    {
     "target": "icarus.tpcwe16.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE17",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 854 },
   "targets": [
    {
     "target": "icarus.tpcwe17.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE18",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 867 },
   "targets": [
    {
     "target": "icarus.tpcwe18.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE19",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 880 },
   "targets": [
    {
     "target": "icarus.tpcwe19.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE20M",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 893 },
   "targets": [
    {
     "target": "icarus.tpcwe20m.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WE20B",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 906 },
   "targets": [
    {
     "target": "icarus.tpcwe20b.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW01M",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 919 },
   "targets": [
    {
     "target": "icarus.tpcww01m.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW01B",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 932 },
   "targets": [
    {
     "target": "icarus.tpcww01b.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW02",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 945 },
   "targets": [
    {
     "target": "icarus.tpcww02.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW03",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 958 },
   "targets": [
    {
     "target": "icarus.tpcww03.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW04",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 971 },
   "targets": [
    {
     "target": "icarus.tpcww04.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW05",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 984 },
   "targets": [
    {
     "target": "icarus.tpcww05.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW06",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 997 },
   "targets": [
    {
     "target": "icarus.tpcww06.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW07",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1010 },
   "targets": [
    {
     "target": "icarus.tpcww07.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW08",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1023 },
   "targets": [
    {
     "target": "icarus.tpcww08.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW09",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1036 },
   "targets": [
    {
     "target": "icarus.tpcww09.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW10",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1049 },
   "targets": [
    {
     "target": "icarus.tpcww10.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW11",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1062 },
   "targets": [
    {
     "target": "icarus.tpcww11.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW12",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1075 },
   "targets": [
    {
     "target": "icarus.tpcww12.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW13",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1088 },
   "targets": [
    {
     "target": "icarus.tpcww13.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW14",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1101 },
   "targets": [
    {
     "target": "icarus.tpcww14.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW15",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1114 },
   "targets": [
    {
     "target": "icarus.tpcww15.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW16",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1127 },
   "targets": [
    {
     "target": "icarus.tpcww16.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW17",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1140 },
   "targets": [
    {
     "target": "icarus.tpcww17.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW18",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1153 },
   "targets": [
    {
     "target": "icarus.tpcww18.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW19",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1166 },
   "targets": [
    {
     "target": "icarus.tpcww19.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW20M",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1179 },
   "targets": [
    {
     "target": "icarus.tpcww20m.BoardReader.*.Temp.*.Temp1"
    }
   ]
  },
  {
   "title": "TPC WW20B",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1192 },
   "targets": [
    {
     "target": "icarus.tpcww20b.BoardReader.*.Temp.*.Temp1"
    }
   ]
  }
 ]
}